//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSCache, NSMutableSet;

@interface _DVTImageCache : NSObject
{
    NSCache *_cache;
    NSMutableSet *_negativeCache;
}

+ (id)sharedCache;
- (void).cxx_destruct;
- (void)_nukeCache;
- (id)cachedImageWithKey:(id)arg1 creationBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

