//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/_TtC6DVTKit35DVTPathControlNavigationPopoverItem.h>

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit46DVTPathControlDescriptiveNavigationPopoverItem : _TtC6DVTKit35DVTPathControlNavigationPopoverItem
{
    // Error parsing type: , name: secondaryText
    // Error parsing type: , name: descriptiveText
}

- (void).cxx_destruct;

@end

