//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/_TtC6DVTKit24DVTNavigationPopoverItem.h>

__attribute__((visibility("hidden")))
@interface _TtC6DVTKit35DVTPathControlNavigationPopoverItem : _TtC6DVTKit24DVTNavigationPopoverItem
{
    // Error parsing type: , name: pathCellItem
}

- (void).cxx_destruct;

@end

