//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSTextField.h>

@class NSImage;

@interface DVTButtonTextField : NSTextField
{
    BOOL _resetingCursorRects;
}

+ (void)setCellClass:(Class)arg1;
+ (Class)cellClass;
+ (void)initialize;
- (void)resetCursorRects;
- (struct CGRect)visibleRect;
- (void)mouseDown:(id)arg1;
@property unsigned long long imagePosition;
@property(readonly) NSImage *highlightImage;
@property(readonly) NSImage *alternateImage;
@property(retain) NSImage *image;
@property SEL buttonAction;
@property __weak id buttonTarget;
- (id)baseImageFromTemplateImage:(id)arg1;

@end

