//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/NSObject-Protocol.h>

@protocol DVTComparisonScrollContentAreaDelegate <NSObject>
- (void)contentAreaWindowOrderedOut;
- (void)contentAreaWindowOrderedIn;
- (void)contentAreaMovedToNewWindow;
- (void)contentAreaRemovedFromSuperview;
- (void)contentAreaDidHide;
- (void)mouseExitedContentArea;
- (void)mouseMovedInContentArea;
- (void)mouseEnteredContentArea;
- (void)contentAreaWillDraw;
@end

