//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/NSObject-Protocol.h>

@class DVTDevice, NSMutableArray, NSString;

@protocol DVTDevicesListItem <NSObject>
@property(readonly) NSMutableArray *children;
@property(readonly, getter=isLeaf) BOOL leaf;
@property(retain) DVTDevice *device;
@property(readonly, getter=isGroupItem) BOOL groupItem;
@property(readonly, getter=isEditable) BOOL editable;
@property(retain) NSString *name;
@end

