//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/DVTWarningTextField.h>

@class DVTExpressionTextFieldCell, NSExpression, NSString;

@interface DVTExpressionTextField : DVTWarningTextField
{
}

+ (void)initialize;
@property(copy) NSExpression *expression;
@property(copy) NSString *initialStringValue;
@property(retain) DVTExpressionTextFieldCell *cell;
- (BOOL)textShouldEndEditing:(id)arg1;
- (BOOL)abortEditing;
- (void)textDidBeginEditing:(id)arg1;

@end

