//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/NSObject-Protocol.h>

@class DVTFindPattern;
@protocol DVTFindPatternField;

@protocol DVTFindPatternManager <NSObject>
- (id <DVTFindPatternField>)replaceFieldForField:(id <DVTFindPatternField>)arg1;
- (id <DVTFindPatternField>)findFieldForField:(id <DVTFindPatternField>)arg1;

@optional
- (BOOL)supportsPatterns;
- (void)findPatternField:(id <DVTFindPatternField>)arg1 findPatternDoubleClicked:(DVTFindPattern *)arg2;
@end

