//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTLocalComputer.h>

@interface DVTLocalComputer (KitAdditions)
- (void)showQuicklookPreviewForExtension:(id)arg1;
- (void)showSiriForExtensions:(id)arg1 queryText:(id)arg2 pid:(int)arg3 onProxy:(BOOL)arg4 completed:(CDUnknownBlockType)arg5;
- (void)showTodayViewForExtensions:(id)arg1 pid:(int)arg2;
- (id)deviceSummaryPropertyDictionaries;
- (id)image;
- (int)deviceWindowCategory;
@end

