//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/DVTFilterExpressionFieldController.h>

@interface DVTTextOnlyFilterExpressionFieldController : DVTFilterExpressionFieldController
{
}

- (id)initWithTokenField:(id)arg1 filteredDataSource:(id)arg2 viewingContext:(id)arg3;

@end

