//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSWindowController.h>

@interface NSWindowController (DVTNSWindowControllerAdditions)
- (id)dvt_windowIfLoaded;
- (void)dvt_clearNibBindings;
- (void)dvt_loadWindowIfNeeded;
@end

