//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderCocoaIntegration/IBNSViewController.h>

@interface IBNSViewController (IDEInterfaceBuilderDFRSupport)
+ (void)ibDFRReplaceIBNSViewControllerInstanceMethods;
- (BOOL)child:(id)arg1 canHostTouchBarInDocument:(id)arg2;
- (id)ibDFRSwizzledWindowWithCopiedViewHierarchySnapshotForLayoutEngine:(id)arg1 returningAddedRepresentedConstraintsForRepresentedViews:(id *)arg2;
- (BOOL)ibDFRShouldAcceptChildTouchBarInDocument:(id)arg1;
- (id)ibHitTestingView;
- (void)ibSwizzledDecodePlatformItems:(id)arg1;
- (void)ibSwizzledEncodePlatformItems:(id)arg1;
@end

