//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IBFoundation/NSObject-Protocol.h>

@class IBICCatalogCompilerOptions, IBICCatalogCompilerResult, NSString;

@protocol IBICCompilableSticker <NSObject>
- (NSString *)itemName;
- (BOOL)compileToPath:(NSString *)arg1 options:(IBICCatalogCompilerOptions *)arg2 results:(IBICCatalogCompilerResult *)arg3;
@end

