//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerFoundation/DYPPluginFactoryCommonDelegate-Protocol.h>

@class DYDeviceInfo, DYShaderProfilerResult;
@protocol DYPPipelineStatistics, DYPResourceManager;

@protocol DYPDebuggerControllerProxyDelegate <DYPPluginFactoryCommonDelegate>
@property(readonly, nonatomic) id <DYPResourceManager> resourceManager;
@property(readonly) id <DYPPipelineStatistics> pipelineStatistics;
@property(readonly) BOOL shaderProfilerResultsHaveBeenUpdated;
@property(readonly) DYShaderProfilerResult *shaderProfilerResultsBase;
@property(readonly) DYShaderProfilerResult *shaderProfilerResults;
@property(readonly) DYDeviceInfo *deviceInfo;
@property(readonly) double appFrameRate;
@end

