//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerFoundation/NSObject-Protocol.h>

@protocol DYPShaderDebuggerExecutionHistoryNode;

@protocol DYPShaderDebuggerThread <NSObject>
@property(readonly, nonatomic) id <DYPShaderDebuggerExecutionHistoryNode> rootNode;
@property(readonly, nonatomic) unsigned long long type;
@end

