//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@interface GPUGlobalStateManager : NSObject
{
    BOOL _showGroupDisplayableCallCount;
}

+ (id)sharedGlobalStateManager;
@property(readonly, nonatomic) BOOL showGroupDisplayableCallCount; // @synthesize showGroupDisplayableCallCount=_showGroupDisplayableCallCount;
- (void)setprogramMetricsShaderPerformanceDifference:(BOOL)arg1;
@property(nonatomic) BOOL programMetricsShaderPerformanceDifference; // @dynamic programMetricsShaderPerformanceDifference;
@property(nonatomic) BOOL programMetricsAsPercentage;
- (BOOL)showGroupDrawCallCount;
@property(nonatomic) BOOL hideShaderProfilingInFrameNavigator;
@property(nonatomic) BOOL compactTextMode;
- (id)_init;
- (id)init;

@end

