//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSString;

@interface GPUGeometryViewerMessage : NSObject
{
    BOOL _noPositionAttribute;
    NSString *_geometryType;
    unsigned long long _instanceCount;
    unsigned long long _elementCount;
    unsigned long long _indexCount;
    double _loadTime;
    unsigned long long _issueCountTotal;
    unsigned long long _issueCountDegenerates;
    unsigned long long _issueCountIndefinites;
    unsigned long long _issueCountDuplicates;
}

@property BOOL noPositionAttribute; // @synthesize noPositionAttribute=_noPositionAttribute;
@property unsigned long long issueCountDuplicates; // @synthesize issueCountDuplicates=_issueCountDuplicates;
@property unsigned long long issueCountIndefinites; // @synthesize issueCountIndefinites=_issueCountIndefinites;
@property unsigned long long issueCountDegenerates; // @synthesize issueCountDegenerates=_issueCountDegenerates;
@property unsigned long long issueCountTotal; // @synthesize issueCountTotal=_issueCountTotal;
@property double loadTime; // @synthesize loadTime=_loadTime;
@property unsigned long long indexCount; // @synthesize indexCount=_indexCount;
@property unsigned long long elementCount; // @synthesize elementCount=_elementCount;
@property unsigned long long instanceCount; // @synthesize instanceCount=_instanceCount;
@property(copy) NSString *geometryType; // @synthesize geometryType=_geometryType;
- (void).cxx_destruct;
- (void)log;

@end

