//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <GPUDebuggerFoundation/DYPlatformSDK-Protocol.h>

@class DVTSDK, NSString, NSURL;

@interface GPUPlatformSDK : NSObject <DYPlatformSDK>
{
    DVTSDK *_dvtSDK;
    NSString *_identifier;
}

+ (id)developerSDKsForGPUSession:(id)arg1 internal:(BOOL)arg2;
+ (id)developerSDKsForGPUSession:(id)arg1;
+ (id)developerSDKForPlatform:(int)arg1 internal:(BOOL)arg2;
+ (id)developerSDKForPlatform:(int)arg1;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)fileURLForExecutableBinary:(id)arg1;
@property(readonly, nonatomic) NSURL *fileURL;
@property(readonly, nonatomic) NSString *operatingSystemVersion;
@property(readonly, nonatomic) NSString *canonicalName;
@property(readonly, nonatomic) BOOL isInternal;
- (int)platformType;
- (id)initWithIdentifier:(id)arg1 dvtSDK:(id)arg2;

@end

