//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerFoundation/GPUTraceOutlineItem.h>

@class GPUTraceResourceItem;

@interface GPUTraceDependencyResourceItem : GPUTraceOutlineItem
{
    GPUTraceResourceItem *_wrappedResource;
}

@property(nonatomic) __weak GPUTraceResourceItem *wrappedResource; // @synthesize wrappedResource=_wrappedResource;
- (void).cxx_destruct;
- (id)APIItem;
- (id)label;
- (id)initWithResourceItem:(id)arg1 withParent:(id)arg2;

@end

