//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerFoundation/GPUTraceGroupItem.h>

@interface GPUTraceCommandBufferGroupItem : GPUTraceGroupItem
{
}

- (id)initWithController:(id)arg1 parent:(id)arg2 identifier:(id)arg3 groupType:(unsigned int)arg4 functionIndex:(int)arg5 descText:(id)arg6;

@end

