//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (ShaderDebugger)
@property(readonly) BOOL GPUDebugger_shaderDebuggerShowIndividualVectorComponents;
@property(readonly) double GPUDebugger_shaderDebuggerDataTipPopoverDelay;
@property(readonly) double GPUDebugger_shaderDebuggerValueViewScale;
@property(readonly) long long GPUDebugger_shaderDebuggerFragmentRegionOfInterestSize;
@property(readonly) double GPUDebugger_shaderDebuggerSidebarWidth;
@end

