//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEIntentBuilderCore/IDEIntentBuilderEnumGroup.h>

#import <IDEIntentBuilderEditor/IDEIntentBuilderGroupEditable-Protocol.h>

@class NSString;

@interface IDEIntentBuilderEnumGroup (EditorAdditions) <IDEIntentBuilderGroupEditable>
- (id)imageName;
@property(readonly, nonatomic, getter=isHiddenWhenEmpty) BOOL hiddenWhenEmpty;

// Remaining properties
@property(readonly) BOOL canEditItems;
@property(readonly) BOOL canRemoveItems;
@property(readonly) BOOL canRenameItems;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

