//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSTextView.h>

#import <IDEIntentBuilderEditor/NSTextStorageDelegate-Protocol.h>

@class NSString;
@protocol IDEIntentBuilderTokenTextViewDataSource;

@interface IDEIntentBuilderTokenTextView : NSTextView <NSTextStorageDelegate>
{
    long long _backgroundStyle;
    unsigned long long _lineBreakMode;
    id <IDEIntentBuilderTokenTextViewDataSource> _dataSource;
}

@property __weak id <IDEIntentBuilderTokenTextViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property unsigned long long lineBreakMode; // @synthesize lineBreakMode=_lineBreakMode;
@property long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
- (void).cxx_destruct;
- (void)textStorage:(id)arg1 didProcessEditing:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4;
- (void)_replaceCharactersInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;
- (BOOL)readSelectionFromPasteboard:(id)arg1 type:(id)arg2;
- (BOOL)writeSelectionToPasteboard:(id)arg1 type:(id)arg2;
- (id)acceptableDragTypes;
- (id)readablePasteboardTypes;
- (id)writablePasteboardTypes;
- (void)insertCompletion:(id)arg1 forPartialWordRange:(struct _NSRange)arg2 movement:(long long)arg3 isFinal:(BOOL)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

