//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEKit/IDEInspectorProperty.h>

@class DVTNotificationToken, DVTObservingToken, IDEInspectorKeyPath, IDEIntentBuilderClassTextField, NSArray;

@interface IDEIntentBuilderIntentCustomClassInspectorProperty : IDEInspectorProperty
{
    IDEInspectorKeyPath *_valueKeyPath;
    DVTNotificationToken *_sourceGenerationNotificationObserver;
    DVTObservingToken *_generatedClassNameObservingToken;
    IDEIntentBuilderClassTextField *_textField;
    NSArray *_generatedIntentFilePaths;
}

@property(retain, nonatomic) NSArray *generatedIntentFilePaths; // @synthesize generatedIntentFilePaths=_generatedIntentFilePaths;
@property __weak IDEIntentBuilderClassTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)_unbind;
- (id)findIndicatorContentViewWithContext:(id)arg1;
- (double)baseline;
- (id)nibName;
- (void)primitiveInvalidate;
- (void)_checkClassLinkEnabled;
- (void)_updateGeneratedIntentClassWithInfo:(id)arg1;
- (void)_updateGeneratedIntentClassWithBuildSettings;
- (void)intentClassButtonClicked:(id)arg1;
- (id)inspectedDocument;
- (id)inspectedIntent;
- (void)userDidChangeClassName:(id)arg1;
- (void)setupRefreshTriggersAndConfigure;
- (void)refresh;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)viewDidLoad;

@end

