//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEIntentBuilderCore/IDEIntentBuilderModel.h>

@class IDEIntentBuilderGroupItem, NSArray;

@interface IDEIntentBuilderModel (EditorAdditions)
+ (id)systemIntentsModel;
+ (id)keyPathsForValuesAffectingCanRemovedSelectedItem;
@property(readonly, nonatomic) NSArray *visibleGroups;
- (void)selectFirstItem;
@property(retain, nonatomic) IDEIntentBuilderGroupItem *selectedItem;
@property(readonly) BOOL canRemovedSelectedItem;
@end

