//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC14XCBBuildSystemP33_74BF0C9CBFAC7DB52D268988B5BDFB1213InProcessTool : _TtCs12_SwiftObject
{
    // Error parsing type: , name: actionType
    // Error parsing type: , name: description
    // Error parsing type: , name: adaptor
}

@end

