//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCBProtocol/_TtC11XCBProtocol18GroupTreeReference.h>

@interface _TtC11XCBProtocol12VersionGroup : _TtC11XCBProtocol18GroupTreeReference
{
    // Error parsing type: , name: children
}

@end

