//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSError, XCSUIService, XCSUIServicesManager;

@protocol XCSUIServicesManagerDelegate
- (void)servicesManager:(XCSUIServicesManager *)arg1 serviceWasAdded:(XCSUIService *)arg2;
- (void)servicesManager:(XCSUIServicesManager *)arg1 serviceWasRemoved:(XCSUIService *)arg2;
- (void)servicesManager:(XCSUIServicesManager *)arg1 didReloadService:(XCSUIService *)arg2 error:(NSError *)arg3;
@end

