//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEIntentBuilderCore/IDEIntentBuilderGroupItem.h>

@class IDEIntentBuilderIntent, NSArray;

@interface IDEIntentBuilderIntentGroupItem : IDEIntentBuilderGroupItem
{
    unsigned long long _lastParameterTag;
    NSArray *_parameters;
}

+ (id)defaultParameterName;
@property(copy, nonatomic) NSArray *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) unsigned long long lastParameterTag; // @synthesize lastParameterTag=_lastParameterTag;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)init;
- (void)_reassignDisplayPriority;
- (void)_removeParameter:(id)arg1 undoHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSArray *supportedTypes;
- (id)parametersWithTypes:(id)arg1;
- (id)parameterTypeWithName:(id)arg1 class:(Class)arg2;
- (id)parameterWithName:(id)arg1;
- (id)parameterWithIdentifier:(id)arg1;
- (void)removeParameter:(id)arg1;
- (void)updateIndexesOfParameters:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)addParameter:(id)arg1;
- (void)resetToggleIntentCategoryIfNeeded;
@property(readonly, nonatomic) IDEIntentBuilderIntent *intent;
- (id)codegen_propertyImplementationsForSourceLanguage:(unsigned long long)arg1 readonly:(BOOL)arg2;
- (id)codegen_propertyDeclarationsForSourceLanguage:(unsigned long long)arg1 readonly:(BOOL)arg2;
- (id)codegen_availabilityForSourceLanguage:(unsigned long long)arg1;

@end

