//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTAnalytics/NSObject-Protocol.h>

@class NSString;

@protocol DVTAnalyticsLogStackFrameProtocol <NSObject>
@property(readonly) NSString *instructionPointerAddressString;
@property(readonly) unsigned long long sourceLine;
@property(readonly) NSString *sourceFile;
@property(readonly) unsigned long long stackFrameOffset;
@property(readonly) NSString *symbol;
@property(readonly) NSString *image;
@end

