//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTAnalytics/DVTAnalyticsPointSymbolicator.h>

@interface DVTCrashPointSymbolicator : DVTAnalyticsPointSymbolicator
{
}

- (void)updateAnalyticsPoint:(id)arg1 withSymbolicatedAnalyticsLog:(id)arg2;
- (unsigned long long)indexMatchingCrashingFrameInFrames:(id)arg1;

@end

