//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTInstrumentsFoundation/DTTapDataMemo.h>

@class DTXMessage, NSData;

@interface DTActivityTraceTapMemo : DTTapDataMemo
{
    DTXMessage *_message;
    NSData *_data;
    unsigned long long _lastMachContinuousTimeSeen;
}

@property(nonatomic) unsigned long long lastMachContinuousTimeSeen; // @synthesize lastMachContinuousTimeSeen=_lastMachContinuousTimeSeen;
- (void).cxx_destruct;
- (const void *)getBufferWithLength:(unsigned long long *)arg1;
- (id)initWithMessage:(id)arg1;
- (id)initWithData:(id)arg1;

@end

