//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@interface DTNetStatTapSupportedAttributes : NSObject
{
}

+ (id)localRouteAttributesNumberMap;
+ (id)localUDPAttributesNumberMap;
+ (id)localTCPAttributesNumberMap;
+ (id)localCountsAttributesNumberMap;
+ (id)localRouteAttributesMap;
+ (id)localUDPAttributesMap;
+ (id)localTCPAttributesMap;
+ (id)localCountsAttributesMap;
+ (id)localRouteAttributes;
+ (id)localUDPAttributes;
+ (id)localTCPAttributes;
+ (id)localCountsAttributes;

@end

