//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTInstrumentsFoundation/DTTapMessage.h>

#import <DVTInstrumentsFoundation/NSSecureCoding-Protocol.h>

@class NSDictionary;

@interface DTSysmonTapMessage : DTTapMessage <NSSecureCoding>
{
    NSDictionary *_runningMetadata;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSDictionary *runningMetadata; // @synthesize runningMetadata=_runningMetadata;
- (void).cxx_destruct;
- (void)setSessionMetadata:(id)arg1;
- (id)sessionMetadata;
@property(nonatomic) unsigned int tapVersion;

@end

