//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

@class NSColor;

@interface DVTAnalyticsPointChartScaffoldView : NSView
{
    NSColor *_debugColor;
}

@property(copy) NSColor *debugColor; // @synthesize debugColor=_debugColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

