//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

#import <IDEProductsUI/DVTTableCellViewStatusView-Protocol.h>

@class NSImageView;

@interface IDEAnalyticsPointStatusView : NSView <DVTTableCellViewStatusView>
{
    BOOL _hasDisplayableStatus;
    NSImageView *_imageView;
}

@property(readonly) NSImageView *imageView; // @synthesize imageView=_imageView;
@property BOOL hasDisplayableStatus; // @synthesize hasDisplayableStatus=_hasDisplayableStatus;
- (void).cxx_destruct;
- (void)setBackgroundStyle:(long long)arg1;
- (id)initWithImageSize:(struct CGSize)arg1 bottomOffset:(double)arg2;

// Remaining properties
@property(nonatomic) long long tableViewRowSizeStyle;

@end

