//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEProducts/IDEProduct.h>

@interface IDEProduct (AnalyticsPointUI)
- (id)analyticsPointSourceCollectionsForType:(long long)arg1;
- (id)sourceForVersion:(id)arg1 forType:(long long)arg2;
@end

