//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSDictionary.h>

@class NSArray;

@interface XCBStablePropertyListDictionary : NSDictionary
{
    NSDictionary *_dictionary;
    NSArray *_orderedKeys;
}

- (void).cxx_destruct;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (unsigned long long)count;
- (id)initWithContents:(id)arg1 memoTable:(id)arg2;

@end

