//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <DNTTransformer/WKScriptMessageHandler-Protocol.h>

@interface _TtCC14DNTTransformer24FullReferenceTransformerP33_273C6788BC37A76B620DF406FC15BADD30ImageLoadFailureMessageHandler : NSObject <WKScriptMessageHandler>
{
    // Error parsing type: , name: handler
}

- (void).cxx_destruct;
- (id)init;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;

@end

