//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSScrollView.h>

@class NSResponder;

__attribute__((visibility("hidden")))
@interface _DTTimelineScrollView : NSScrollView
{
    NSResponder *_nextMagnificationResponder;
}

+ (BOOL)isCompatibleWithResponsiveScrolling;
@property(retain, nonatomic) NSResponder *nextMagnificationResponder; // @synthesize nextMagnificationResponder=_nextMagnificationResponder;
- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;
- (void)magnifyWithEvent:(id)arg1;

@end

