//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEiPhoneSupport/DVTiPhoneSubController.h>

@class DVTiOSScreenshotClient, NSMutableDictionary, NSObject;
@protocol OS_os_log;

@interface DVTiPhoneScreenshotController : DVTiPhoneSubController
{
    NSMutableDictionary *_requestDict;
    void *_connection;
    BOOL transferSuccess;
    BOOL _screenshotPending;
    NSObject<OS_os_log> *_log;
    DVTiOSScreenshotClient *_screenshotClient;
}

+ (id)keyPathsForValuesAffectingScreenshots;
@property BOOL screenshotPending; // @synthesize screenshotPending=_screenshotPending;
@property(retain) DVTiOSScreenshotClient *screenshotClient; // @synthesize screenshotClient=_screenshotClient;
@property(retain) NSObject<OS_os_log> *log; // @synthesize log=_log;
- (void).cxx_destruct;
- (id)initWithDevice:(id)arg1;
- (void)addCapturedScreenshot:(id)arg1;
- (void)sendFileError:(id)arg1;
- (void)sendFileDone:(id)arg1;
- (void)connectionLost:(id)arg1;
- (void)connectionFailed:(id)arg1;
- (void)_notifyRequestFailedWithMessage:(id)arg1;
- (void)_synchronousScreenShotRequest;
- (void)requestScreenshotModern;
- (void)requestScreenshotLegacy;
- (void)requestScreenshot;
- (_Bool)canTakeScreenshot;
- (void)_connectToDevice;
- (void *)getDefaultConnection;
- (struct __CFDictionary *)requestDict;
- (void)primitiveInvalidate;
- (void)closeConnection;
- (void)setStatusText:(id)arg1;
- (id)screenshots;
- (id)globalController;

@end

