//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC23DNTDocumentationSupport20UncompressedDataView : _TtCs12_SwiftObject
{
    // Error parsing type: , name: compressedData
    // Error parsing type: , name: uncompressedData
    // Error parsing type: , name: stream
}

@end

