//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSOperation.h>

__attribute__((visibility("hidden")))
@interface _TtC23DNTDocumentationSupport24BulkEnumerationOperation : NSOperation
{
    // Error parsing type: , name: documentationService
    // Error parsing type: , name: dataRange
    // Error parsing type: , name: entitySuccessHandler
    // Error parsing type: , name: entityParseFailureHandler
    // Error parsing type: , name: imageHandler
    // Error parsing type: , name: otherFailureHandler
}

- (void).cxx_destruct;
- (id)init;
- (void)main;

@end

