//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DebuggerUI/IDEDebuggingAddition-Protocol.h>

@protocol DBGCoreAnimationDebuggingAddition <IDEDebuggingAddition>

@optional
@property(nonatomic) BOOL flashUpdatedRegions;
@property(nonatomic) BOOL colorCopiedImages;
@property(nonatomic) BOOL colorBlendedLayers;
@property(nonatomic) BOOL colorMisalignedImages;
@property(nonatomic) BOOL colorImmediately;
@property(nonatomic) BOOL colorOpenGLFastPathBlue;
@property(nonatomic) BOOL colorOffscreenRenderedYellow;
@property(nonatomic) BOOL colorCached;
@property(nonatomic) BOOL colorFormats;
@end

