//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DebuggerUI/NSObject-Protocol.h>

@class DBGDebugNavigatorContentDelegate;

@protocol DBGDebugNavigatorContentObjectDelegate <NSObject>
- (void)openSelectedObjectWithEventType:(unsigned long long)arg1 contentDelegate:(DBGDebugNavigatorContentDelegate *)arg2;

@optional
- (BOOL)supportsUserInterfaceCopyActionWithContentDelegate:(DBGDebugNavigatorContentDelegate *)arg1;
- (BOOL)supportsUserInterfaceDeleteActionWithContentDelegate:(DBGDebugNavigatorContentDelegate *)arg1;
- (void)handleUserDirectDeleteWithContentDelegate:(DBGDebugNavigatorContentDelegate *)arg1;
@end

