//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class SCNView;

@protocol DBGPixelPerfectAdjusting
@property double offsetZ;
@property double offsetY;
@property double offsetX;
- (void)adjustPixelPerfectForView:(SCNView *)arg1;
@end

