//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

@interface DBGRectInspectorPropertyView : NSView
{
    struct CGRect _rect;
}

@property struct CGRect rect; // @synthesize rect=_rect;
- (struct CGRect)scaledRectForRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

