//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEStackFrame.h>

#import <DebuggerUI/DBGDebugNavigatorContentObjectDataSource-Protocol.h>

@class NSString;

@interface IDEStackFrame (DBGDebugNavigatorContentObjectDataSource) <DBGDebugNavigatorContentObjectDataSource>
+ (void)registerTableCellViewsForDebugNavigatorContentDelegateWithOutlineView:(id)arg1;
- (id)pasteboardStringWithDebugNavigatorContentDelegate:(id)arg1;
- (BOOL)shouldSelectItemWithPrevious:(id)arg1 next:(id)arg2 contentDelegate:(id)arg3;
- (void)setCurrentFrameIndicatorIsVisible:(BOOL)arg1 inRootNavigableItem:(id)arg2 withOutlineView:(id)arg3;
- (id)createThreadsStackContentTableRowViewForWithContentDelegate:(id)arg1;
- (id)createDebugNavigatorTableCellViewWithContentDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

