//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCSCore/XCSObject.h>

@class NSString;

@interface XCSHardwareInfo : XCSObject
{
}


// Remaining properties
@property(readonly, copy) NSString *computerName; // @dynamic computerName;
@property(readonly, copy) NSString *hardwareUUID; // @dynamic hardwareUUID;
@end

