//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCSCore/XCSDevice.h>

@class XCSIntegration;

@interface XCSTestDevice : XCSDevice
{
    XCSIntegration *integration;
}

@property(nonatomic) __weak XCSIntegration *integration; // @synthesize integration;
- (void).cxx_destruct;
- (id)description;

@end

