//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DevToolsCore/PBXProjectItem.h>

@class NSArray, NSDictionary, NSSet, PBXBuildPhase, PBXReference, XCBuildInfo;
@protocol DVTMacroExpansion;

@interface PBXBuildFile : PBXProjectItem
{
    PBXBuildPhase *_buildPhase;
    PBXReference *_fileRef;
    XCBuildInfo *_buildInfo;
    BOOL _hasBuildPhase;
    BOOL _hasOverridingCompilerArgs;
    unsigned int _commonAttrs;
    NSSet *_otherAttrs;
    NSArray<DVTMacroExpansion> *_addlCompilerArgs;
    NSSet *_assetTags;
    NSDictionary *_unknownSettings;
}

+ (void)batchSetAdditionalCompilerArguments:(id)arg1 forBuildFiles:(id)arg2;
+ (id)archivableWeakRelationshipsForPListArchiver:(id)arg1;
+ (id)archivableRelationships;
+ (id)archivableAttributes;
+ (id)buildFileWithReference:(id)arg1;
- (void).cxx_destruct;
- (BOOL)archiveInPlistOnSingleLine;
- (id)gidCommentForArchive;
- (id)buildFileForAbsolutePath:(id)arg1;
- (id)targetBuildContext;
- (id)displayName;
- (id)preprocessingInfoForIndexing;
- (id)buildInfo;
- (void)setStringValueForPrimaryAttribute:(id)arg1;
- (id)stringValueForPrimaryAttribute;
- (id)primaryAttribute;
- (long long)compareType:(id)arg1;
- (long long)compareName:(id)arg1;
- (long long)compareFullPath:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)buildContext;
- (void)setAssetTags:(id)arg1;
- (id)assetTags;
- (long long)headerVisibility;
- (void)setOverridingAdditionalCompilerArguments:(id)arg1;
- (id)overridingAdditionalCompilerArguments;
- (void)_setAdditionalCompilerArguments:(id)arg1 isBatch:(BOOL)arg2;
- (void)setAdditionalCompilerArguments:(id)arg1;
- (id)additionalCompilerArguments;
- (void)setBoolValue:(BOOL)arg1 ofAttributeNamed:(id)arg2;
- (BOOL)boolValueOfAttributeNamed:(id)arg1;
- (id)attributes;
- (void)_setSettings:(id)arg1;
- (void)_addAssetTagsToProjectKnownTags;
- (BOOL)shouldArchiveSettings;
- (id)_settings;
- (void)_upgradeAfterAwakingFromUnarchiver:(id)arg1;
- (void)_setBooleanValue:(BOOL)arg1 ofAttributeNamed:(id)arg2;
- (BOOL)_booleanValueOfAttributeNamed:(id)arg1;
- (void)setContainer:(id)arg1;
- (void)willChange;
- (id)container;
- (id)target;
- (void)_setBuildPhase:(id)arg1;
- (id)buildPhase;
- (id)projectRelativePath;
- (id)resolvedAbsolutePath;
- (id)absolutePath;
- (id)path;
- (id)name;
- (id)fileReference;
- (id)innerDescription;
- (id)initWithReference:(id)arg1;

@end

