//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DevToolsCore/PBXBundleProductType.h>

@interface PBXFrameworkProductType : PBXBundleProductType
{
}

- (void)generateStubAPIForLinkedProductWithMacroExpansionScope:(id)arg1;
- (void)generateInstallAPIForLinkedProductWithMacroExpansionScope:(id)arg1;
- (void)createTBDSymlinksForLinkedProductWithMacroExpansionScope:(id)arg1 forFileName:(id)arg2;
- (void)registerSwiftmoduleProductStructureCreatorsWithMacroExpansionScope:(id)arg1;
- (id)wrapperSubpathForSwiftmodule;
- (void)registerCoreProductStructureCreatorsWithMacroExpansionScope:(id)arg1;
- (void)addBaseLinkerFlagsWithMacroExpansionScope:(id)arg1;
- (void)computeProductDependenciesWithMacroExpansionScope:(id)arg1;

@end

