//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DevToolsCore/PBXJambaseTarget.h>

@interface PBXWrappedTarget : PBXJambaseTarget
{
}

+ (id)targetTypeDisplayName;
- (BOOL)canPackageHeaders;
- (id)fullProductName;
- (id)fullProductNameForConfigurationNamed:(id)arg1;
- (id)wrapperPathExtension;
- (id)wrapperPathExtensionForConfigurationNamed:(id)arg1;
- (id)productNameForConfigurationNamed:(id)arg1;
- (id)productReferenceExpectedFileTypeForConfigurationNamed:(id)arg1;

@end

