//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DevToolsCore/XCEmbeddedBinaryValidator.h>

@interface XCEmbeddedWatchBinaryValidator : XCEmbeddedBinaryValidator
{
}

+ (BOOL)infoDictionaryMatchesWatchKitApp:(id)arg1;
+ (BOOL)infoDictionaryMatchesWatchKitExtension:(id)arg1;
- (BOOL)isValidWithWatchKitAppInfo:(id)arg1 watchKitExtensionInfo:(id)arg2 certOfBundleAtPath:(id)arg3 error:(id *)arg4;
- (BOOL)isValidWithError:(id *)arg1;
- (BOOL)verifyBundleInfoWithWatchKitAppInfo:(id)arg1 watchKitExtensionInfo:(id)arg2 error:(id *)arg3;
- (id)watchAppBundleIdentifierFromExtenstionInfoDictionary:(id)arg1;

@end

