//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class DVTExtension, NSDictionary, NSSet, NSString;

@interface XCInterfaceBuilderCompilerPlatformDefinition : NSObject
{
    NSDictionary *_targetedDeviceFamilyIdentifierToTargetDeviceName;
    DVTExtension *_extension;
    NSString *_explicitTargetDeviceName;
    NSSet *_supportedPlatformNames;
    NSSet *_explicitLinkerOutputFileNames;
}

@property(readonly, nonatomic) NSSet *explicitLinkerOutputFileNames; // @synthesize explicitLinkerOutputFileNames=_explicitLinkerOutputFileNames;
@property(readonly, nonatomic) NSSet *supportedPlatformNames; // @synthesize supportedPlatformNames=_supportedPlatformNames;
@property(readonly, nonatomic) NSString *explicitTargetDeviceName; // @synthesize explicitTargetDeviceName=_explicitTargetDeviceName;
- (void).cxx_destruct;
- (id)description;
- (id)targetDeviceNameForTargetedDeviceFamilyIdentifier:(id)arg1;
- (id)initWithDVTExtension:(id)arg1;

@end

