//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEProductType.h>

#import <DevToolsCore/IDEProductTypeProvider-Protocol.h>

@class DVTPlatform, NSString, XCProductTypeSpecification;

@interface Xcode3ProductType : IDEProductType <IDEProductTypeProvider>
{
    DVTPlatform *_platform;
    XCProductTypeSpecification *_backingSpecification;
}

+ (id)productTypeForIdentifier:(id)arg1 platform:(id)arg2;
@property(readonly) XCProductTypeSpecification *backingSpecification; // @synthesize backingSpecification=_backingSpecification;
- (id)platform;
- (void).cxx_destruct;
- (long long)provisioningProfileSupport;
- (BOOL)runsDirectlyOnProxy;
- (BOOL)willEmbedRunSanitizerLibraries;
- (BOOL)runsOnProxy;
- (BOOL)installsOnProxy;
- (BOOL)shouldAutocreateSchemes;
- (BOOL)isWatch2AppExtension;
- (BOOL)isWatch1AppExtension;
- (BOOL)isWatchAppExtension;
- (BOOL)isWatchApplication;
- (BOOL)isWatch1Application;
- (BOOL)isWatch2Application;
- (BOOL)isAppExtension;
- (BOOL)isApplication;
- (BOOL)isKindOfProductType:(id)arg1;
- (id)superType;
- (id)localizedDescription;
- (id)name;
- (id)identifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

