//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEStandardTestable.h>

@class Xcode3Target;
@protocol DVTInvalidation;

@interface Xcode3Testable : IDEStandardTestable
{
    Xcode3Target *_target;
    id <DVTInvalidation> _blueprintsObserver;
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingTestableProvider;
@property(retain) Xcode3Target *target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)blueprintsDidChange:(id)arg1;
- (id)primaryBuildable;
- (BOOL)isUITest;
- (id)name;
- (id)testableProvider;
- (void)primitiveInvalidate;
- (id)initWithTarget:(id)arg1;

@end

