//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTModelObject.h>

@class NSArray, NSString;

@interface Xcode3LibraryGroup : DVTModelObject
{
}


// Remaining properties
@property(readonly) NSArray *libraries; // @dynamic libraries;
@property(readonly) NSString *name; // @dynamic name;
@end

