//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTModelObject.h>

#import <DevToolsCore/DVTInvalidation-Protocol.h>
#import <DevToolsCore/IDEBlueprint-Protocol.h>
#import <DevToolsCore/IDEIndexable-Protocol.h>
#import <DevToolsCore/IDEMutableProvisionable-Protocol.h>
#import <DevToolsCore/Xcode3SourceListItemEditing-Protocol.h>

@class DVTFilePath, DVTStackBacktrace, DVTToolsVersion, IDEActivityLogSection, IDEPIFGUID, IDETestBlueprintHostSettings, IDETypeIdentifier, NSArray, NSDictionary, NSMapTable, NSMutableArray, NSMutableDictionary, NSNumber, NSOrderedSet, NSSet, NSString, PBXTarget, Xcode3Project, Xcode3TargetCapabilitiesContext;
@protocol IDEBuildable, IDEIndexable, IDEProvisionable;

@interface Xcode3Target : DVTModelObject <IDEBlueprint, IDEIndexable, Xcode3SourceListItemEditing, DVTInvalidation, IDEMutableProvisionable>
{
    PBXTarget *_pbxTarget;
    Xcode3Project *_project;
    NSArray *_buildables;
    NSArray *_buildableProducts;
    id <IDEBuildable> _primaryBuildable;
    NSMutableDictionary *_productHeaders;
    NSString *_cachedIdentifier;
    NSString *_cachedBlueprintIdentifier;
    NSString *_cachedIndexName;
    id _targetDidChangeNotificationObservingToken;
    id _fileWasAddedNotificationObservingToken;
    id _fileWillBeRemovedNotificationObservingToken;
    id _filePathDidChangeNotificationObservingToken;
    id _fileWasAddedToGroupNotificationObservingToken;
    id _fileWillBeRemovedFromGroupNotificationObservingToken;
    id _targetSettingsDidChangeNotificationObservingToken;
    id _projectIntegrityLogDidChangeNotificationObservingToken;
    id _targetProductSettingsDidChangeNotificationObservingToken;
    id _buildOperationDidStopNotificationObservingToken;
    id _targetNameDidChangeNotificationObservingToken;
    id _capabilitiesDidChangeNotificationObservingToken;
    id _availableConfigurationNamesDidChangeObservingToken;
    id _projectSettingsDidChangeObservingToken;
    IDEActivityLogSection *_issueLog;
    NSMutableArray *_watchedFilesForIntegrityLog;
    id <IDEIndexable> _proxy;
    BOOL _headermapsUpToDate;
    BOOL _integrityCheckingBlockQueued;
    unsigned long long _buildSettingsCacheInvalidatedCounter;
    NSSet *_allPublicHeaderFileReferences;
    NSSet *_allPrivateHeaderFileReferences;
    NSSet *_allProjectHeaderFileReferences;
    NSMapTable *_extraSettingsCompletionBlocks;
    NSDictionary *_filePathsToSourceFileBuildInfos;
    NSNumber *_migratedProvisoningStyle;
    Xcode3TargetCapabilitiesContext *_capabilitiesContext;
}

+ (id)keyPathsForValuesAffectingConfigurations;
+ (id)deserializedSourceListItem:(id)arg1;
+ (id)pasteboardDataType;
+ (id)appCategoryDisplayValues;
+ (id)validAppCategories;
+ (id)keyPathsForValuesAffectingName;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (void)initialize;
@property(retain, nonatomic) Xcode3TargetCapabilitiesContext *capabilitiesContext; // @synthesize capabilitiesContext=_capabilitiesContext;
@property(nonatomic) __weak id <IDEIndexable> proxy; // @synthesize proxy=_proxy;
@property(retain) IDEActivityLogSection *issueLog; // @synthesize issueLog=_issueLog;
@property(readonly) Xcode3Project *project; // @synthesize project=_project;
@property(retain) PBXTarget *pbxTarget; // @synthesize pbxTarget=_pbxTarget;
- (void).cxx_destruct;
- (id)sourceFileBuildInfoForFileAtPath:(id)arg1;
- (id)provisioningCommandInputsForConfiguration:(id)arg1 macroExpansionScope:(id)arg2 runDestination:(id)arg3;
- (void)noteProvisioningInputsChanged;
- (void)createEntitlementsFileWithDefaultEntitlements:(id)arg1;
- (unsigned long long)entitlementsDestinationForConfigurationNamed:(id)arg1;
- (unsigned long long)_entitlementsDestinationFromMacroExpansionScope:(id)arg1;
- (id)entitlementsExpansionForConfigurationNamed:(id)arg1;
- (id)_entitlementsExpansionFromMacroExpansionScope:(id)arg1;
- (id)baseEntitlementsForConfigurationNamed:(id)arg1;
- (id)_baseEntitlementsFromMacroExpansionScope:(id)arg1;
- (id)entitlementsFilePathForConfigurationNamed:(id)arg1;
- (id)_entitlementsFilePathFromMacroExpansionScope:(id)arg1;
- (id)bundleIdentifierForConfigurationNamed:(id)arg1;
- (id)_bundleIdentifierFromMacroExpansionScope:(id)arg1 configuration:(id)arg2;
- (void)setSigningCertificateIdentifier:(id)arg1 forConfigurationNamed:(id)arg2;
- (id)signingCertificateIdentifierForConfigurationNamed:(id)arg1;
- (id)_signingCertificateIdentifierFromMacroExpansionScope:(id)arg1;
- (void)setProvisioningProfile:(id)arg1 forConfigurationNamed:(id)arg2;
- (id)legacyProvisioningProfileUUIDForConfigurationNamed:(id)arg1;
- (id)provisioningProfileSpecifierForConfigurationNamed:(id)arg1;
- (id)_provisioningProfileSpecifierFromMacroExpansionScope:(id)arg1;
- (id)appIDFeaturesForConfigurationNamed:(id)arg1;
- (id)appIDFeaturesForConfigurationNamed:(id)arg1 entitlements:(id)arg2 withEntitlementsExpansion:(id)arg3;
- (BOOL)_signingRequiredFromMacroExpansionScope:(id)arg1;
- (BOOL)signingRequiresTeamForConfigurationNamed:(id)arg1;
- (BOOL)_signingRequiresTeamFromMacroExpansionScope:(id)arg1;
- (BOOL)allowSigningWithoutTeamSelectionForConfigurationNamed:(id)arg1;
- (BOOL)_allowSigningWithoutTeamSelectionFromMacroExpansionScope:(id)arg1;
- (id)platformForConfigurationNamed:(id)arg1;
- (id)_platformFromMacroExpansionScope:(id)arg1;
@property(readonly, nonatomic) NSOrderedSet *configurations;
- (long long)profileSupportForConfigurationNamed:(id)arg1;
- (long long)_profileSupportForSDK:(id)arg1 configuration:(id)arg2;
@property(readonly) id <IDEProvisionable> provisionable;
- (void)removeTagsFromKnownAssetTags:(id)arg1;
- (void)addTagsToKnownAssetTags:(id)arg1;
@property(readonly) NSSet *knownAssetTags;
- (id)entitlementsFilePathForBuildConfiguration:(id)arg1;
- (void)_respondToProjectSettingsDidChangeNotification:(id)arg1;
- (void)_respondToAvailableConfigurationNamesDidChangeNotification:(id)arg1;
- (void)_respondToCapabilitiesDidChangeBroadcast:(id)arg1;
- (void)_respondToProjectIntegrityLogDidChangeNotification:(id)arg1;
- (void)_respondToBuildOperationDidStopNotification:(id)arg1;
- (void)_respondToTargetNameDidChangeNotification:(id)arg1;
- (void)_respondToTargetProductSettingsDidChangeNotification:(id)arg1;
- (void)_respondToTargetSettingsDidChangeNotification:(id)arg1;
- (void)_respondToFileWillBeRemovedFromGroupNotification:(id)arg1;
- (void)_respondToFileWasAddedToGroupNotification:(id)arg1;
- (void)_respondToFilePathChangedNotification:(id)arg1;
- (void)_respondToBuildFileRemovedNotification:(id)arg1;
- (void)_respondToBuildFileAddedNotification:(id)arg1;
- (void)_respondToTargetDidChangeNotification:(id)arg1;
- (id)serializedSourceListItem;
- (id)toolSearchPathWithBuildParameters:(id)arg1;
- (id)stringsByEvaluatingPropertyString:(id)arg1 inAllConfigurationsForWorkspaceArenaSnapshot:(id)arg2;
- (id)absolutePathByEvaluatingBuildSettingExpressionString:(id)arg1 withBuildParameters:(id)arg2;
- (id)stringByEvaluatingBuildSettingExpressionString:(id)arg1 withBuildParameters:(id)arg2;
- (id)evaluatedStringListValueForBuildSetting:(id)arg1 withBuildParameters:(id)arg2;
- (id)evaluatedStringValueForBuildSetting:(id)arg1 withBuildParameters:(id)arg2;
- (id)allBuildSettingNamesWithBuildParameters:(id)arg1;
- (id)cachedMacroExpansionScopeForBuildParameters:(id)arg1;
@property(readonly, copy) NSString *productType;
- (id)productNameWithBuildSetting:(id)arg1 workspace:(id)arg2;
- (id)_legacyBuildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (id)_modernBuildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (id)buildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
@property(readonly, copy) NSString *localizedIndexableDescription;
- (void)languageOfMainFile:(id)arg1 workspace:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (BOOL)writeProductHeaders:(id)arg1 toFile:(id)arg2 error:(id *)arg3;
- (void)productHeadersInWorkspace:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)_processSettingsForFilesInWorkspace:(id)arg1 wasSuccessful:(BOOL)arg2 shouldWriteAuxiliaryFiles:(BOOL)arg3 isModern:(BOOL)arg4 withCompletionBlock:(CDUnknownBlockType)arg5 extraBlocks:(id)arg6;
- (id)_buildFileReferencesByFlatteningVariantGroups:(id)arg1;
- (void)_legacySettingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (void)__modernSettingsForFilesInWorkspace:(id)arg1 provider:(id)arg2 shouldWriteAuxiliaryFiles:(BOOL)arg3 withCompletionBlock:(CDUnknownBlockType)arg4 extraBlocks:(id)arg5;
- (void)_modernSettingsForFilesInWorkspace:(id)arg1 provider:(id)arg2 shouldWriteAuxiliaryFiles:(BOOL)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (void)settingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 queue:(id)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (void)settingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (void)settingsForFilesInWorkspace:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)_buildParametersForIndexingInWorkspace:(id)arg1;
- (void)_performDependentBlockWithWorkspace:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(readonly, copy) NSArray *indexableFiles;
- (id)_targetBuildContext;
- (BOOL)_projectIsValid;
- (id)containerForIndexables:(id)arg1 rootPaths:(id)arg2;
@property(readonly, copy) NSString *indexName;
@property(readonly) BOOL requiresMainThread;
@property(readonly, copy) NSString *identifier;
- (void)_indexingRespondToFilePathChangedNotification:(id)arg1;
- (void)_indexingRespondToVariantGroupNotification:(id)arg1 withNewName:(id)arg2;
- (void)_indexingRespondToBuildFileNotification:(id)arg1 withNewName:(id)arg2;
- (void)clearCachedBuildSettings;
- (void)analyzeModelForIssues;
- (id)infoDictionaryFilePathForConfiguration:(id)arg1;
- (id)resolvedInfoDictionaryForBuildParameters:(id)arg1;
- (id)infoDictionaryForConfiguration:(id)arg1;
@property(readonly, copy) DVTFilePath *bundleBaselineRecordFilePath;
- (id)provisioningPurposeForConfigurationNamed:(id)arg1;
- (id)_provisioningPurposeFromMacroExpansionScope:(id)arg1;
- (void)setProvisioningStyle:(long long)arg1 forConfigurationNamed:(id)arg2;
- (long long)provisioningStyleForConfigurationNamed:(id)arg1;
- (long long)_provisioningStyleFromMacroExpansionScope:(id)arg1;
- (long long)_migrateToProvisioningStyle;
- (void)setTeam:(id)arg1 forConfigurationNamed:(id)arg2;
- (BOOL)_areAllConfigurationsAutomaticallyProvisioned;
- (id)teamForConfigurationNamed:(id)arg1;
- (id)_teamFromMacroExpansionScope:(id)arg1;
@property(readonly, getter=isUnitTest) BOOL unitTest;
@property(retain) IDETestBlueprintHostSettings *testBlueprintHostSettings;
@property(retain) IDETestBlueprintHostSettings *testBlueprintUITestingTargetAppSettings;
- (id)additionalOverridingCompilerArgumentsForSourceCodeBuildFileReference:(id)arg1;
- (void)setOverridingAdditionalCompilerArguments:(id)arg1 forSourceCodeBuildFileReference:(id)arg2;
- (id)additionalCompilerArgumentsForSourceCodeBuildFileReference:(id)arg1;
- (void)setAdditionalCompilerArguments:(id)arg1 forSourceCodeBuildFileReference:(id)arg2;
- (id)_pbxBuildFileForFileReference:(id)arg1;
- (id)linkedBinaries;
- (id)allProjectHeaderFiles;
- (id)allPrivateHeaderFiles;
- (id)allPublicHeaderFiles;
- (void)cachePublicPrivateProjectHeaders;
- (int)visibilityOfHeaderBuildFile:(id)arg1;
@property(readonly) BOOL containsOnlySwift;
@property(readonly) BOOL containsSwift;
- (id)localizableSourceBuildFileReferences;
- (id)sourceCodeBuildFileReferences;
- (id)allResourceFilesBreakingOutLocalizableVariants:(BOOL)arg1;
- (id)allBuildFileReferences;
- (BOOL)configureToBuildMixedTargetWithDestinationGroup:(id)arg1 configureBridgingHeader:(BOOL)arg2 returningErrorString:(id *)arg3;
- (BOOL)isConfiguredToBuildMixedTarget;
- (BOOL)wouldBecomeMixedTargetAfterAddingTypes:(id)arg1;
- (BOOL)wouldBecomeMixedTargetAfterAddingFiles:(id)arg1;
- (BOOL)canUseBridgingHeader;
- (BOOL)isMixedTarget;
- (id)predominantSourceCodeLanguage;
- (BOOL)configureToBuildWithOptimizationProfileReturningErrorString:(id *)arg1;
- (BOOL)shouldEnablePGOForConfiguration:(id)arg1;
- (BOOL)isConfiguredToBuildWithOptimizationProfile;
- (void)setEnableSwift3ObjCInference:(BOOL)arg1;
- (void)updateSwiftCompilerTo:(id)arg1;
- (void)resetLastSwiftMigration;
- (void)updateLastSwiftMigrationToCurrent;
- (BOOL)shouldOfferSwift3ObjCInferenceConfiguration;
@property(readonly) BOOL lastSwiftMigrationIsCurrent;
- (void)updateLastSwiftUpdateVersionToCurrent;
@property(readonly) NSString *lastSwiftUpdateVersion;
- (void)convertToUseModernObjCSyntax;
- (BOOL)canEnableCodeGenerationForIBAndAssetCatalogsAndPerformChanges:(BOOL)arg1;
- (void)convertToEnableCodeGenerationForIBAndAssetCatalogs;
- (BOOL)canConvertToEnableCodeGenerationForIBAndAssetCatalogs;
- (void)convertToUseARC;
- (void)_updateSDKIfNeeded;
- (void)_updateSDKIfNeededInConfigurations:(id)arg1;
- (void)_updateMacDeploymentTargetIfNeeded:(id)arg1;
- (BOOL)canConvertToUseARC;
- (void)convertToBuild64bitOnly;
- (void)convertToUseClang;
- (void)removeFileReferenceFromBuildables:(id)arg1;
- (void)addFileReference:(id)arg1 toBuildablesContainingFileReference:(id)arg2;
@property(readonly, copy) NSString *compilerSpecificationIdentifier;
- (id)customDataStore;
- (id)supportedPlatformsForConfiguration:(id)arg1 workspaceArenaSnapshot:(id)arg2;
- (id)supportedPlatformsForBuildParameters:(id)arg1;
- (id)availableArchitecturesForConfiguration:(id)arg1 workspaceArenaSnapshot:(id)arg2;
- (id)availableArchitecturesForBuildParameters:(id)arg1;
@property(readonly, copy) NSString *defaultConfigurationName;
@property(readonly, copy) NSArray *availableConfigurationNames;
@property(readonly) NSArray *buildableProducts;
@property(readonly) NSArray *buildables;
@property(readonly) id <IDEBuildable> primaryBuildable;
- (id)buildableForIdentifier:(id)arg1;
@property(readonly, copy) NSString *blueprintIdentifier;
@property(readonly, copy) NSString *localizedDescription;
- (id)blueprintProvider;
- (void)setName:(id)arg1;
@property(readonly, copy) NSString *name;
- (id)ideModelObjectTypeIdentifier;
@property(readonly, copy) NSString *description;
- (BOOL)containsFilePath:(id)arg1;
- (BOOL)containsFileReference:(id)arg1;
- (id)_referenceForFileReference:(id)arg1;
@property(readonly) DVTToolsVersion *createdOnToolsVersion;
- (id)pathToLargestAssetCatalogAppIconPassingTest:(CDUnknownBlockType)arg1;
@property(readonly) BOOL isXPCServiceTarget;
@property(readonly) BOOL isAutomatorActionTarget;
- (BOOL)_isProductBundleWithExtension:(id)arg1;
@property(readonly) NSString *iconPath;
@property(readonly) NSString *infoPlistFilePath;
@property(readonly) NSString *productModuleName;
@property(readonly) NSSet *namesOfLinkedBinaries;
- (id)specifiedBaseSDKForBuildConfigurationName:(id)arg1;
- (id)baseSDKForBuildConfigurationName:(id)arg1;
- (id)deviceSDKFor:(id)arg1 SDKs:(id)arg2;
- (id)simulatorSDKFor:(id)arg1 SDKs:(id)arg2;
- (void)primitiveInvalidate;
- (id)initWithTarget:(id)arg1 project:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)supportedSourceListItemEditorClasses;
- (id)infoPlistFileReference;

// Remaining properties
@property(readonly, copy) IDEPIFGUID *PIFGUID;
@property(readonly) IDETypeIdentifier *activityLogDomainType;
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) BOOL participatesInSchemeAutocreation;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

