//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DevToolsCore/PBXProjectItem.h>

#import <DevToolsCore/XCCompatibilityChecking-Protocol.h>

@class NSString, PBXProject;

@interface XCSwiftPackageReference : PBXProjectItem <XCCompatibilityChecking>
{
    PBXProject *_project;
}

- (void).cxx_destruct;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (void)findFeaturesInUseAndAddToSet:(id)arg1 usingPathPrefix:(id)arg2;
- (void)setContainer:(id)arg1;
- (id)container;
@property(readonly, nonatomic) NSString *displayVersionRules;
@property(readonly, nonatomic) NSString *displayLocation;
@property(readonly, nonatomic) NSString *displayName;
- (void)packageReferenceDidChange;
- (void)packageReferenceWillChange;

@end

