//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSDictionary, XCMacroExpansionScope;

@interface XCWorkQueueCommandBuiltinInvocation_infoPlistUtility_CustomInfo : NSObject
{
    XCMacroExpansionScope *_macroExpansionScope;
    NSDictionary *_additionalContent;
}

@property(retain) NSDictionary *additionalContent; // @synthesize additionalContent=_additionalContent;
@property(retain) XCMacroExpansionScope *macroExpansionScope; // @synthesize macroExpansionScope=_macroExpansionScope;
- (void).cxx_destruct;

@end

