//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <DevToolsCore/XCOutputStreams-Protocol.h>

@class DVTSystemStatisticsMeasurement, IDEActivityLogSection, NSString, XCWorkQueueCommandInvocationParameters;
@protocol XCOutputStreams, XCWorkQueueCommands;

@interface XCWorkQueueCommandInvocation : NSObject <XCOutputStreams>
{
    id <XCWorkQueueCommands> _command;
    IDEActivityLogSection *_activityLogSection;
    NSString *_fileProgressDescriptionFormat;
    XCWorkQueueCommandInvocationParameters *_invocationParameters;
    id <XCOutputStreams> _outputStream;
    unsigned long long _numberOfMessages;
    DVTSystemStatisticsMeasurement *_systemStatsAtStart;
    DVTSystemStatisticsMeasurement *_systemStatsAtFinish;
}

@property(copy) XCWorkQueueCommandInvocationParameters *invocationParameters; // @synthesize invocationParameters=_invocationParameters;
@property(retain) IDEActivityLogSection *activityLogSection; // @synthesize activityLogSection=_activityLogSection;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (double)elapsedSystemTime;
- (double)elapsedUserTime;
- (id)systemStatisticsDelta;
- (id)systemStatisticsAtFinish;
- (id)systemStatisticsAtStart;
- (void)_warnAboutUseOfPBXJambaseRuleDescriptionForProgressDescription;
- (void)_warnAboutUseOfPBXJambaseRuleDescriptionForExecutionDescription;
- (unsigned long long)messageLimit;
- (void)emitBuildMessageOfType:(int)arg1 withFormat:(id)arg2;
- (void)emitBuildMessageOfType:(int)arg1 toTranscript:(BOOL)arg2 withFormat:(id)arg3;
- (void)emitBuildMessageOfType:(int)arg1 message:(id)arg2 forFileAtPath:(id)arg3 lineNumber:(unsigned long long)arg4;
- (void)emitBuildMessageOfType:(int)arg1 toTranscript:(BOOL)arg2 message:(id)arg3 forFileAtPath:(id)arg4 lineNumber:(unsigned long long)arg5;
- (id)absolutePathForPath:(id)arg1;
- (void)close;
- (void)flush;
- (void)writeBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (void)cancelAndWaitUntilFinished;
- (void)handleInputFileDescriptorActivity;
- (void)handleOutputFileDescriptorActivity;
- (void)handleEndOfOutput;
- (void)handleOutputBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (BOOL)startRunning;
- (int)exitCode;
@property(readonly) BOOL isCancelled;
- (BOOL)isRunning;
- (int)inputFileDescriptor;
- (int)outputFileDescriptor;
- (void)stopRecordingBuildOutput;
@property(readonly) NSString *fileProgressDescriptionFormat;
- (id)_toolSpecification;
- (id)command;
- (id)initWithWorkQueueCommand:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

