//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <XCTDaemonControlMobileDevice/XCTDaemonDTXConnectionProviding-Protocol.h>

@class NSString, XCTMobileDevice;
@protocol XCTDebugLogDelegate, XCTRemoteHostDiagnosticReportsSynchronizing;

@interface XCTMobileDeviceDTXConnectionProvider : NSObject <XCTDaemonDTXConnectionProviding>
{
    id <XCTDebugLogDelegate> _logDelegate;
    NSString *_serviceName;
    NSString *_identifier;
    XCTMobileDevice *_mobileDevice;
}

@property(retain) XCTMobileDevice *mobileDevice; // @synthesize mobileDevice=_mobileDevice;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property __weak id <XCTDebugLogDelegate> logDelegate; // @synthesize logDelegate=_logDelegate;
- (void).cxx_destruct;
@property(readonly) id <XCTRemoteHostDiagnosticReportsSynchronizing> remoteHostDiagnosticReportsSynchronizer;
- (void)invalidate;
- (void)makeConnectionWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithMobileDeviceIdentifier:(id)arg1 serviceName:(id)arg2;
- (id)initWithMobileDeviceIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

