//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderKit/IBInspectorViewController.h>

@interface IBCocoaTouchInspectorViewController : IBInspectorViewController
{
    BOOL _allInspectedDocumentsSupportAdaptiveSegues;
    BOOL _allInspectedDocumentsSupportLegacySegues;
}

+ (id)keyPathsForValuesAffectingInspectingStoryboard;
@property(nonatomic) BOOL allInspectedDocumentsSupportLegacySegues; // @synthesize allInspectedDocumentsSupportLegacySegues=_allInspectedDocumentsSupportLegacySegues;
@property(nonatomic) BOOL allInspectedDocumentsSupportAdaptiveSegues; // @synthesize allInspectedDocumentsSupportAdaptiveSegues=_allInspectedDocumentsSupportAdaptiveSegues;
- (void)updateVisibilityFlags;
@property(readonly, nonatomic) BOOL showLegacySeguesHeading;
@property(readonly) BOOL inspectingStoryboard;

@end

