//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderKit/IBDocument.h>

@interface IBDocument (IBDocumentCocoaTouchIntegration)
+ (id)keyPathsForValuesAffectingCocoaTouchTargetRuntime;
+ (id)keyPathsForValuesAffectingDefaultUISimulatedMetricsContainer;
+ (int)libraryInclusionStatusForWindow;
+ (int)libraryInclusionStatusForProxyObject;
- (void)printStatusForCocoaTouchTools:(id)arg1;
- (void)shutdownCachedCocoaTouchTools:(id)arg1;
- (void)switchOrientationManyTimes:(id)arg1;
- (id)viewControllerRepresentativeForObject:(id)arg1;
- (void)unarchiveCocoaTouchDataWithDocumentUnarchiver:(id)arg1;
- (void)archiveCocoaTouchDataWithDocumentArchiver:(id)arg1;
- (BOOL)isNonExistentAtRuntimePlaceholder:(id)arg1;
- (long long)lastSavedPluginVersion;
- (id)cocoaTouchIdiom;
- (id)cocoaTouchPlatform;
- (id)cocoaTouchTargetRuntime;
- (BOOL)compilesSeparateContentOnIOSVersionsPriorToEight;
- (BOOL)canTargetIOS7;
- (BOOL)isCocoaTouchDocument;
- (void)setBaseInheritedScreenMetrics:(id)arg1 orientationMetrics:(id)arg2;
- (id)defaultUISimulatedMetricsContainer;
@end

