//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@interface IBPreXcode8ColorCorrector : NSObject
{
}

- (void)decodePlatformSpecificDocumentProperties:(id)arg1;
- (void)encodePlatformSpecificDocumentProperties:(id)arg1;
- (void)unarchivePlatformSpecificDocumentProperties:(id)arg1;
- (void)archivePlatformSpecificDocumentProperties:(id)arg1;
- (int)detectColorHandlerGivenDecodingStack:(id)arg1 isGlobalTintColor:(BOOL)arg2;

@end

