//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBUIView.h>

#import <IDEInterfaceBuilderCocoaTouchIntegration/IBDocumentArchiving-Protocol.h>

@class NSString;

@interface IBUIWindow : IBUIView <IBDocumentArchiving>
{
    BOOL _visibleAtLaunch;
    BOOL _resizesToFullScreen;
}

+ (void)registerMarshallingRecordHandlers;
+ (int)ibLibraryInclusionStatusForTargetRuntime:(id)arg1 andDocumentClass:(Class)arg2 assetIdentifier:(id)arg3;
@property BOOL resizesToFullScreen; // @synthesize resizesToFullScreen=_resizesToFullScreen;
@property(getter=isVisibleAtLaunch) BOOL visibleAtLaunch; // @synthesize visibleAtLaunch=_visibleAtLaunch;
- (id)effectiveSimulatedMetrics;
- (BOOL)canPresentSimulatedMetrics;
- (struct CGRect)internalStatusBarFrame;
- (id)runtimeClassNameForContext:(id)arg1 returningOptionalFallbackClassName:(id *)arg2;
- (BOOL)prefersCachedImageBasedDrawing;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)ibInspectedSupportsBottomBarMetrics;
- (BOOL)ibInspectedSupportsTopBarMetrics;
- (struct CGSize)ibPreferredSize;
- (BOOL)doesSizeMatchLegacyIPhoneFullScreenSize:(struct CGSize)arg1;
- (BOOL)ibIsUserSizable;
- (BOOL)ibUsesWidgetTypeForTypeNameForDefaultLabel;
- (id)ibWidgetType;
- (id)ibPasteboardTypes;
- (id)ibDesignableContentView;
- (Class)ibEditorClass;
- (id)ibLocalAttributeKeyPaths;
- (void)unarchiveWithDocumentUnarchiver:(id)arg1;
- (void)archiveWithDocumentArchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

