//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <GPUToolsServices/NSCopying-Protocol.h>
#import <GPUToolsServices/NSSecureCoding-Protocol.h>

@class DYInvestigatorRecommendationInfo, DYInvestigatorRecommendationSection, NSMutableDictionary;

@interface DYInvestigatorRecommendation : NSObject <NSCopying, NSSecureCoding>
{
    NSMutableDictionary *_sectionsDict;
    DYInvestigatorRecommendationSection *_currentSection;
    DYInvestigatorRecommendationInfo *_summary;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) DYInvestigatorRecommendationInfo *summary; // @synthesize summary=_summary;
- (void).cxx_destruct;
- (void)printFormatted;
- (void)addAdditionalSectionItem:(id)arg1;
- (void)addSpecificSectionItem:(id)arg1;
- (void)addGeneralSectionItem:(id)arg1;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *additionalSection;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *specificSection;
@property(readonly, nonatomic) DYInvestigatorRecommendationSection *generalSection;
- (void)setOrdered:(BOOL)arg1;
- (void)setPreamble:(id)arg1;
- (void)selectSection:(id)arg1;
- (void)setSummaryWithString:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)description;

@end

