//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface DYMetalLibraryToolsService : NSObject
{
    struct dispatch_queue_s *_queue;
    int _platform;
    NSDictionary *_platformURLs;
    BOOL _thinLibraryFallback;
}

- (void).cxx_destruct;
- (BOOL)_executeTask:(id)arg1 arguments:(id)arg2 workingDirectory:(id)arg3 description:(id)arg4 error:(id *)arg5;
- (id)_buildLibraryWithOptions:(id)arg1 targetFilename:(id)arg2 directoryURL:(id)arg3 error:(id *)arg4;
- (BOOL)_compileSourceWithOptions:(id)arg1 directoryURL:(id)arg2 error:(id *)arg3;
- (id)_extractSourceFromMetallib:(id)arg1 directoryURL:(id)arg2 error:(id *)arg3;
- (id)_extractFunctionDependenciesFromMetallib:(id)arg1 directoryURL:(id)arg2 error:(id *)arg3;
- (id)_targetLibraryFilenameForBuild:(unsigned long long)arg1 stripped:(BOOL)arg2;
- (id)_readBuildLogAtURL:(id)arg1;
- (void)_writeBuildLog:(id)arg1 atURL:(id)arg2;
- (id)_addBuildOptionsToCompileOptions:(id)arg1 buildFlags:(unsigned long long)arg2;
- (id)_sanitizeCompileOptions:(id)arg1 buildFlags:(unsigned long long)arg2;
- (id)_retrieveBuildOptionsAndCompileTargetsForFunction:(id)arg1 sourceAtURL:(id)arg2 error:(id *)arg3;
- (id)_retrieveBuildOptionsAndCompileTargetsForSourceAtURL:(id)arg1 modifiedFileURLs:(id)arg2 error:(id *)arg3;
- (id)_retrieveCompileOptionsForTarget:(id)arg1 sourceURL:(id)arg2 error:(id *)arg3;
- (void)_createDependencyTargetMapForExtractedSourceAtURL:(id)arg1 error:(id *)arg2;
- (BOOL)_compileBuildTargets:(id)arg1 sourceAtURL:(id)arg2 flags:(unsigned long long)arg3 error:(id *)arg4;
- (void)buildLibraryForFunction:(id)arg1 sourceAtURL:(id)arg2 flags:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)buildLibraryWithSourceAtURL:(id)arg1 flags:(unsigned long long)arg2 modifiedFileURLs:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)extractSourceFromLibraryAtURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithCaptureStore:(id)arg1;
- (id)initWithCaptureStore:(id)arg1 platformSDK:(id)arg2;

@end

