//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC7XCBCoreP33_E1C7224AF68B481F922A0855296183E015SettingsBuilder : _TtCs12_SwiftObject
{
    // Error parsing type: , name: context
    // Error parsing type: , name: sdkRegistry
    // Error parsing type: , name: parameters
    // Error parsing type: , name: project
    // Error parsing type: , name: target
    // Error parsing type: , name: provisioningTaskInputs
    // Error parsing type: , name: signing
    // Error parsing type: , name: deploymentTarget
    // Error parsing type: , name: forBindingProperties
    // Error parsing type: , name: includeExports
    // Error parsing type: , name: targetConfiguration
    // Error parsing type: , name: productType
    // Error parsing type: , name: packageType
    // Error parsing type: , name: preferredArch
    // Error parsing type: , name: sdk
    // Error parsing type: , name: sdkVariant
    // Error parsing type: , name: userNamespace
    // Error parsing type: , name: _table
    // Error parsing type: , name: exportedMacroNames
    // Error parsing type: , name: exportedNativeMacroNames
    // Error parsing type: , name: exportedMacroIDs
    // Error parsing type: , name: exportedNativeIDs
    // Error parsing type: , name: errors
    // Error parsing type: , name: warnings
    // Error parsing type: , name: macroConfigPaths
    // Error parsing type: , name: macroConfigSignatureCache
}

@end

