//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC7XCBCoreP33_C7927A06EBA0E00A838F05F5A408ED7620DiscoveredTargetInfo : _TtCs12_SwiftObject
{
    // Error parsing type: , name: immediateDependencies
    // Error parsing type: , name: packageProductDependencies
}

@end

