//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCBCore/_TtC7XCBCore18GroupTreeReference.h>

@interface _TtC7XCBCore13FileReference : _TtC7XCBCore18GroupTreeReference
{
    // Error parsing type: , name: fileTypeIdentifier
    // Error parsing type: , name: regionVariantName
    // Error parsing type: , name: fileTextEncoding
}

@end

