//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCBCore/_TtC7XCBCore4Spec.h>

@interface _TtC7XCBCore18PropertyDomainSpec : _TtC7XCBCore4Spec
{
    // Error parsing type: , name: buildOptions
    // Error parsing type: , name: deletedOptionNames
    // Error parsing type: , name: flattenedBuildOptionsCache
    // Error parsing type: , name: flattenedOrderedBuildOptionsCache
}

@end

