//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <ModelIO/MDLComponent-Protocol.h>

@class MDLAnimatedScalarArray, NSArray;

@protocol MDLMorphDeformerComponent <MDLComponent>
@property(readonly, nonatomic) MDLAnimatedScalarArray *weights;
@property(readonly, nonatomic) NSArray *shapeSetTargetCounts;
@property(readonly, nonatomic) NSArray *shapeSetTargetWeights;
@property(readonly, nonatomic) NSArray *targetShapes;
@end

