//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerMTLSupport/NSObject-Protocol.h>

@class NSDictionary, NSError, NSString, NSURL;
@protocol DYResource;

@protocol DYPShaderUpdaterDelegate <NSObject>
@property(nonatomic) int disableReason;
@property(nonatomic) BOOL shadersUpdatable;
- (void)shaderUpdatedWithStatus:(BOOL)arg1 resource:(id <DYResource>)arg2;
- (void)shaderUpdateDidEnd:(id <DYResource>)arg1 error:(NSError *)arg2;
- (void)shaderUpdateDidBegin;
- (void)defaultLibraryUpdateRequested:(NSURL *)arg1 updateBlock:(void (^)(NSData *))arg2;
- (void)setInfoDictForProgram:(unsigned long long)arg1 dict:(NSDictionary *)arg2 container:(unsigned long long)arg3;
- (NSDictionary *)infoDictForProgram:(unsigned long long)arg1 container:(unsigned long long)arg2;
- (NSString *)appRunnableLocation;
@end

