//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerMTLSupport/DYPPluginFactoryCommonDelegate-Protocol.h>

@class NSBundle, NSImage, NSString;
@protocol DYPVariablesViewGPUStateValue;

@protocol DYPVariablesViewContentProviderDelegate <DYPPluginFactoryCommonDelegate>
@property(readonly, nonatomic) int textMode;
@property(readonly, nonatomic) int comparisonMode;
- (NSImage *)defaultImageWithIssueType:(int)arg1 ofSize:(unsigned long long)arg2;
- (NSImage *)cachedImageWithName:(NSString *)arg1 fromBundle:(NSBundle *)arg2;
- (BOOL)isRuntimeOSAppleInternal;
- (void)addVariableNodeFromDataValue:(id <DYPVariablesViewGPUStateValue>)arg1 type:(unsigned long long)arg2 recipientArray:(struct NSMutableArray *)arg3;
- (void)bubbleUpChangeStatusHighlighting:(id <DYPVariablesViewGPUStateValue>)arg1;
- (void)setEmptyVarView;
- (id <DYPVariablesViewGPUStateValue>)newStateValue;
@end

