//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPUDebuggerFoundation/GPUDebuggerController.h>

#import <GPUDebuggerMTLSupport/DYPShaderUpdaterDelegate-Protocol.h>

@class DVTFilePath, DVTObservingToken, DYMTLAnalyzerArchiveVisitor, NSArray, NSMutableArray, NSObject, NSString;
@protocol DYPDebuggerControllerProxy, DYPDependencyGraph, DYPShaderUpdater, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface GPUMTLDebuggerController : GPUDebuggerController <DYPShaderUpdaterDelegate>
{
    DYMTLAnalyzerArchiveVisitor *_analyzerVisitor;
    NSArray *_invalidOverridesCache;
    DVTObservingToken *_overviewSamplesObserver;
    NSMutableArray *_overviewSampleArray;
    DVTFilePath *_defaultLibraryPath;
    BOOL _updateDefaultLibrary;
    id <DYPDebuggerControllerProxy> _platformDebuggerController;
    id <DYPShaderUpdater> _shaderUpdater;
    id <DYPDependencyGraph> _dependencyGraph;
    int _disableReason;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _shadersUpdatable;
    NSArray *_invalidOverrides;
}

+ (id)assetBundle;
@property(nonatomic) int disableReason; // @synthesize disableReason=_disableReason;
@property(nonatomic) BOOL shadersUpdatable; // @synthesize shadersUpdatable=_shadersUpdatable;
- (void).cxx_destruct;
- (id)gpuVendorForAPIItem:(id)arg1;
- (id)gpuNameForAPIItem:(id)arg1;
- (id)invalidOverrides;
- (void)defaultLibraryUpdateRequested:(id)arg1 updateBlock:(CDUnknownBlockType)arg2;
- (void)setInfoDictForProgram:(unsigned long long)arg1 dict:(id)arg2 container:(unsigned long long)arg3;
- (id)infoDictForProgram:(unsigned long long)arg1 container:(unsigned long long)arg2;
- (void)shaderUpdatedWithStatus:(BOOL)arg1 resource:(id)arg2;
- (void)shaderUpdateDidEnd:(id)arg1 error:(id)arg2;
- (void)shaderUpdateDidBegin;
- (BOOL)wantsDerivedCounters;
- (BOOL)analyzeStoredCaptureArchive;
- (void)requestPerLineShaderProfilerData:(unsigned long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)isDisassemblerAvailable;
- (id)runShaderProfiler:(unsigned long long)arg1;
- (void)traceSessionEstablishedWithNewArchive:(BOOL)arg1;
- (BOOL)_configureInvestigatorWithCaseConfigData:(id)arg1;
- (id)createProgramPerformanceReportProvider:(id)arg1;
- (id)createInvestigatorReportProvider:(id)arg1;
- (void)createReportWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)updateShaders;
- (void)handleDocumentChanged:(id)arg1 shaderItem:(id)arg2;
- (void)resetResourceManagerWithResourceStreamer:(id)arg1;
- (BOOL)handleCaptureSessionFinalization:(id)arg1;
- (void)setupCaptureSessionInfoWithArchive:(id)arg1;
- (void)handleAppSessionTransportMessage:(id)arg1;
- (void)setupGuestAppSession:(id)arg1;
- (id)newGuestAppSessionWithGuestApp:(id)arg1 device:(id)arg2 deferLaunch:(BOOL)arg3 error:(id *)arg4;
- (void)createModelFactory;
- (void)setDeviceInfo:(id)arg1;
- (BOOL)supportsInvestigator;
- (void)primitiveInvalidate;
- (id)init;
- (void)setupCaptureSession:(id)arg1;
- (id)dependencyGraph;
- (id)appRunnableLocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

