//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEiOSSupportCore/DVTTestDevice-Protocol.h>

@class NSString;
@protocol DVTInvalidation, DVTTestingSimDevice, DVTTestingiPhoneSimulator;

@protocol DVTTestingiPhoneSimulator <DVTTestDevice>
+ (id <DVTTestingiPhoneSimulator>)simulatorWithDevice:(id <DVTTestingSimDevice>)arg1;
@property(readonly) id <DVTTestingSimDevice> device;
- (id <DVTInvalidation>)claimDeviceForToken:(NSString *)arg1;
@end

