//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEiOSSupportCore/IDEDistributionMethodAdHoc.h>

@interface IDEDistributionMethodDevelopmentSigned : IDEDistributionMethodAdHoc
{
}

- (id)provisioningProfilePurpose;
- (id)certificateKind;
- (id)subtitle;
- (id)shortTitle;
- (id)title;
- (id)commandLineName;
- (id)supportedPlatform;
- (double)sortOrder;

@end

