//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEDistributionMethodAppStore.h>

@interface IDEDistributionMethodiOSAppStore : IDEDistributionMethodAppStore
{
}

- (id)distributionOptionIdentifiers;
- (id)packagingStepIdentifierForDestination:(long long)arg1;
- (id)provisioningProfilePlatform;
- (long long)wantsProvisioningProfiles;
- (id)installerCertificateKind;
- (id)certificateKind;
- (id)supportedPlatform;
- (_Bool)supportsDistributionOfArchive:(id)arg1;

@end

