//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class LOCITSRulesFile, NSArray, NSDictionary, NSMutableArray, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface LOCHandler : NSObject
{
    NSOperationQueue *_queue;
    NSOperationQueue *_ibfilesQueue;
    NSMutableArray *_importedFiles;
    NSObject<OS_dispatch_queue> *_importedFilesQueue;
    NSMutableArray *_importedFileDescriptions;
    NSObject<OS_dispatch_queue> *_importedFileDescriptionsQueue;
    NSMutableArray *_exportRequests;
    NSString *_sourceLocale;
    NSString *_ITSRulesFilePath;
    NSString *_destinationURL;
    NSString *_projectDirPath;
    NSDictionary *_toolInfo;
    LOCITSRulesFile *_rulesFile;
}

@property(retain) LOCITSRulesFile *rulesFile; // @synthesize rulesFile=_rulesFile;
@property(copy) NSDictionary *toolInfo; // @synthesize toolInfo=_toolInfo;
@property(copy) NSString *projectDirPath; // @synthesize projectDirPath=_projectDirPath;
@property(readonly, copy) NSString *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(readonly, copy) NSString *ITSRulesFilePath; // @synthesize ITSRulesFilePath=_ITSRulesFilePath;
@property(copy) NSString *sourceLocale; // @synthesize sourceLocale=_sourceLocale;
@property(readonly, copy) NSArray *importedFileDescriptions; // @synthesize importedFileDescriptions=_importedFileDescriptions;
@property(readonly, copy) NSArray *importedFiles; // @synthesize importedFiles=_importedFiles;
- (void).cxx_destruct;
- (id)_recordFileNotInImportIssue:(id)arg1 importComparisonFile:(id)arg2 projectComparisonFile:(id)arg3;
- (id)_recordFileNotInProjectIssue:(id)arg1 importComparisonFile:(id)arg2 projectComparisonFile:(id)arg3;
- (id)_compareImportUnrecognizedExtensionFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportJavaScriptStringsFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportIntentdefinitionFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportStickersFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportStringsdictFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportHTMLFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportRTFFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportIBFileWithIBTool:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportIBFileWithOntology:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportIBFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportStringsFile:(id)arg1 withGeneratedFiles:(id)arg2 writeTempComparisonFilesTo:(id)arg3;
- (id)_compareImportStringsFile:(id)arg1 writeTempComparisonFilesTo:(id)arg2;
- (id)_compareImportGlossary:(id)arg1 projectGlossary:(id)arg2 writeTempComparisonFilesTo:(id)arg3;
- (id)_compareGlossary:(id)arg1 withProjectFiles:(id)arg2 generatedFiles:(id)arg3 writeTempComparisonFilesTo:(id)arg4;
- (id)_compareGlossary:(id)arg1 withProjectFiles:(id)arg2 writeTempComparisonFilesTo:(id)arg3;
- (id)_compareNonxliffableFilesInPath:(id)arg1 withProjectFiles:(id)arg2;
- (void)_handleImportUnrecognizedExtensionFile:(id)arg1;
- (void)_handleImportJavaScriptStringsFile:(id)arg1;
- (void)_handleImportIntentdefinitionFile:(id)arg1;
- (void)_handleImportStickersFile:(id)arg1;
- (void)_handleImportStringsdictFile:(id)arg1;
- (void)_handleImportHTMLFile:(id)arg1;
- (void)_handleImportRTFFile:(id)arg1;
- (void)_handleImportIBFileWithIBTool:(id)arg1;
- (void)_handleImportIBFileWithOntology:(id)arg1;
- (void)_handleImportIBFile:(id)arg1;
- (void)_handleImportStringsFile:(id)arg1 withGeneratedFiles:(id)arg2;
- (void)_handleImportStringsFile:(id)arg1;
- (void)_addImportedFile:(id)arg1 withInfoFromSourceDescription:(id)arg2;
- (void)_addImportedFileDescription:(id)arg1;
- (void)_addImportedFile:(id)arg1;
- (void)_importGlossaryEntryWithPath:(id)arg1 glossary:(id)arg2 sourceFile:(id)arg3 generatedFiles:(id)arg4;
- (void)_importGlossaryEntryWithPath:(id)arg1 glossary:(id)arg2 sourceFile:(id)arg3;
- (BOOL)_findXliff:(id)arg1 xliffPath:(id *)arg2 error:(id *)arg3;
- (void)_prepareForImportOfDocument:(id)arg1 toFiles:(id)arg2 xliffPath:(id *)arg3 importAll:(BOOL)arg4 error:(id *)arg5;
- (id)_xliffDocFromFile:(id)arg1 error:(id *)arg2;
- (void)_postFileNotification:(id)arg1 forFile:(id)arg2 description:(id)arg3 error:(id)arg4;
- (void)_postNotification:(id)arg1 userInfo:(id)arg2;
- (void)_createRulesFileWithPath:(id)arg1;
- (id)_existingTargetFileForPath:(id)arg1 inLprojForLocale:(id)arg2 error:(id *)arg3;
- (BOOL)_isXliffable:(id)arg1;
- (BOOL)_isIBFile:(id)arg1;
- (void)importLocalizationsForFiles:(id)arg1 fromFile:(id)arg2 ITSRulesPath:(id)arg3 projDirPath:(id)arg4 importAll:(BOOL)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)importLocalizationsForFiles:(id)arg1 fromFile:(id)arg2 ITSRulesPath:(id)arg3 projDirPath:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)importFromFile:(id)arg1 ITSRulesPath:(id)arg2 projDirPath:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)compareImportContents:(id)arg1 toProjectSourceFiles:(id)arg2 ITSRulesPath:(id)arg3 projDirPath:(id)arg4 writeTempComparisonFilesTo:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)exportLocalizedFiles:(id)arg1 referenceFiles:(id)arg2 outputPath:(id)arg3 sourceLocale:(id)arg4 targetLocale:(id)arg5 ITSRulesPath:(id)arg6 projDirPath:(id)arg7 completionHandler:(CDUnknownBlockType)arg8;
- (void)exportLocalizedFiles:(id)arg1 outputPath:(id)arg2 sourceLocale:(id)arg3 targetLocale:(id)arg4 ITSRulesPath:(id)arg5 projDirPath:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)processLocalizedFiles:(id)arg1 outputPath:(id)arg2 sourceLocale:(id)arg3 targetLocale:(id)arg4 ITSRulesPath:(id)arg5 projDirPath:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (Class)exportRequestClass;
- (void)cancel;
- (id)initWithSourceLocale:(id)arg1 itsRulesPath:(id)arg2 projectDirPath:(id)arg3 toolInfo:(id)arg4;
- (id)initWithSourceLocale:(id)arg1 itsRulesPath:(id)arg2 projectDirPath:(id)arg3;
- (id)init;

@end

