//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Localization/LOCExportRequest.h>

@class NSFileManager, NSString;

@interface LOCXclocExportRequest : LOCExportRequest
{
    NSFileManager *_fileManager;
    NSString *_sourceContentsPath;
    NSString *_localizedContentsPath;
    NSString *_referencesPath;
}

@property(readonly, copy) NSString *referencesPath; // @synthesize referencesPath=_referencesPath;
@property(readonly, copy) NSString *localizedContentsPath; // @synthesize localizedContentsPath=_localizedContentsPath;
@property(readonly, copy) NSString *sourceContentsPath; // @synthesize sourceContentsPath=_sourceContentsPath;
- (void).cxx_destruct;
- (BOOL)_handleExportNonXLIFFableFile:(id)arg1 error:(id *)arg2;
- (id)_xliffOutputPath;
- (BOOL)_copyReferenceFile:(id)arg1 error:(id *)arg2;
- (BOOL)_prepareForFileExportWithFileDescription:(id)arg1 error:(id *)arg2;
- (id)_generateContentsJSON;
- (BOOL)_copyingSourceFilesWithError:(id *)arg1;
- (id)initWithHandler:(id)arg1 localizedFiles:(id)arg2 referenceFiles:(id)arg3 outputPath:(id)arg4 targetLocale:(id)arg5 ITSRulesFilePath:(id)arg6 queue:(id)arg7 ibFilesQueue:(id)arg8;

@end

