//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class IDEDocNavigatorArea, NSURL;

@protocol IDEDocNavigatorAreaDelegate
- (void)navigatorArea:(IDEDocNavigatorArea *)arg1 didSelectURL:(NSURL *)arg2;
@end

