//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEDocViewer/NSObject-Protocol.h>

@protocol IDETabbedWindowController <NSObject>
- (void)newTab:(id)arg1;
- (void)newWindow:(id)arg1;
- (void)newWindowForTab:(id)arg1;
@end

