//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Xcode3UI/Xcode3BuildRuleViewController.h>

@class DVTBorderedView, DVTGradientImageButton, DVTScrollView, DVTStackView_ML, DVTTableView, NSPopUpButton, NSTextField, NSView, _TtC8Xcode3UI44Xcode3PegasusCustomBuildRuleSourceEditorView;

__attribute__((visibility("hidden")))
@interface _TtC8Xcode3UI42Xcode3PegasusCustomBuildRuleViewController : Xcode3BuildRuleViewController
{
    // Error parsing type: , name: frameChangeToken
    // Error parsing type: , name: delayedUpdateLayoutInvocation
    // Error parsing type: , name: scriptChangeDelayedInvocation
    // Error parsing type: , name: fileTypePopUpButton
    // Error parsing type: , name: fileExtensionTextField
    // Error parsing type: , name: buildCommandPopUpButton
    // Error parsing type: , name: scriptSourceEditorView
    // Error parsing type: , name: scriptBorderedView
    // Error parsing type: , name: outputFilesTableView
    // Error parsing type: , name: outputFilesScrollView
    // Error parsing type: , name: outputFilesBorderedView
    // Error parsing type: , name: addOutputFileButton
    // Error parsing type: , name: removeOutputFilesButton
    // Error parsing type: , name: topSliceView
    // Error parsing type: , name: scriptSliceView
    // Error parsing type: , name: outputFilesTableSliceView
    // Error parsing type: , name: outputFilesButtonsSliceView
    // Error parsing type: , name: stackView
    // Error parsing type: , name: unknownCompilerSpecificationTitle
    // Error parsing type: , name: _PBXBuildRuleModuleFileTypeDummyItem
    // Error parsing type: , name: _PBXBuildRuleModuleCompilerSpecDummyItem
    // Error parsing type: , name: outputFilesColumnIdentifier
    // Error parsing type: , name: compilerFlagsColumnIdentifier
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)removeOutputFilesButtonAction:(id)arg1;
- (void)addOutputFileButtonAction:(id)arg1;
- (void)buildCommandPopUpButtonAction:(id)arg1;
- (void)fileTypePopUpButtonAction:(id)arg1;
- (void)focusOnScriptView:(id)arg1;
- (void)capsuleView:(id)arg1 setTitle:(id)arg2;
- (void)capsuleViewDidClickRemoveButton:(id)arg1;
- (BOOL)tableView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)viewDidLoad;
- (void)primitiveInvalidate;
@property(nonatomic, retain) DVTStackView_ML *stackView; // @synthesize stackView;
@property(nonatomic, retain) NSView *outputFilesButtonsSliceView; // @synthesize outputFilesButtonsSliceView;
@property(nonatomic, retain) NSView *outputFilesTableSliceView; // @synthesize outputFilesTableSliceView;
@property(nonatomic, retain) NSView *scriptSliceView; // @synthesize scriptSliceView;
@property(nonatomic, retain) NSView *topSliceView; // @synthesize topSliceView;
@property(nonatomic, retain) DVTGradientImageButton *removeOutputFilesButton; // @synthesize removeOutputFilesButton;
@property(nonatomic, retain) DVTGradientImageButton *addOutputFileButton; // @synthesize addOutputFileButton;
@property(nonatomic, retain) DVTBorderedView *outputFilesBorderedView; // @synthesize outputFilesBorderedView;
@property(nonatomic, retain) DVTScrollView *outputFilesScrollView; // @synthesize outputFilesScrollView;
@property(nonatomic, retain) DVTTableView *outputFilesTableView; // @synthesize outputFilesTableView;
@property(nonatomic, retain) DVTBorderedView *scriptBorderedView; // @synthesize scriptBorderedView;
@property(nonatomic, retain) _TtC8Xcode3UI44Xcode3PegasusCustomBuildRuleSourceEditorView *scriptSourceEditorView; // @synthesize scriptSourceEditorView;
@property(nonatomic, retain) NSPopUpButton *buildCommandPopUpButton; // @synthesize buildCommandPopUpButton;
@property(nonatomic, retain) NSTextField *fileExtensionTextField; // @synthesize fileExtensionTextField;
@property(nonatomic, retain) NSPopUpButton *fileTypePopUpButton; // @synthesize fileTypePopUpButton;

@end

