//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Xcode3UI/Xcode3BuildPropertyDefinitionCustomEnumNodeAdapter.h>

@interface _TtC8Xcode3UI47Xcode3BuildPropertyDefinitionSDKRootNodeAdapter : Xcode3BuildPropertyDefinitionCustomEnumNodeAdapter
{
}

- (id)init;
- (id)_buildPropertyEditor;
- (id)menuItemForUnknownValue:(id)arg1 existingItems:(id)arg2;
- (void)addMenuItemsToPopUpCell:(id)arg1;

@end

