//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Xcode3UI/Xcode3StringListBuildPropertyEditor.h>

@interface Xcode3PathListBuildPropertyEditor : Xcode3StringListBuildPropertyEditor
{
}

- (id)stringsFromDictionaries:(id)arg1;
- (id)dictionariesFromStrings:(id)arg1;
- (long long)columnForAutoEditing;
- (struct CGSize)minimumEditorSizeForContent:(id)arg1;

@end

