//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEModelEditor/IDEIndexContainerSymbol-Protocol.h>

@class IDEIndexCollection;

@protocol IDEIndexClassSymbol <IDEIndexContainerSymbol>
- (IDEIndexCollection *)interfaces;
- (IDEIndexCollection *)allProtocols;
- (IDEIndexCollection *)protocols;
- (IDEIndexCollection *)allSubclasses;
- (IDEIndexCollection *)subclasses;
- (IDEIndexCollection *)allSuperclasses;
- (IDEIndexCollection *)superclasses;
- (IDEIndexCollection *)categories;
- (IDEIndexCollection *)gkInspectableProperties;
- (IDEIndexCollection *)ibOutletCollectionProperties;
- (IDEIndexCollection *)ibOutletCollectionVariables;
- (IDEIndexCollection *)ibOutletCollections;
- (IDEIndexCollection *)ibOutletProperties;
- (IDEIndexCollection *)ibOutletVariables;
- (IDEIndexCollection *)ibOutlets;
- (IDEIndexCollection *)ibActionMethods;
- (IDEIndexCollection *)properties;
- (IDEIndexCollection *)instanceVariables;
- (IDEIndexCollection *)classVariables;
- (IDEIndexCollection *)instanceMethods;
- (IDEIndexCollection *)classMethods;
@end

