//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTAnalyticsClient/DVTAnalyticsData.h>

@class _TtC18DVTAnalyticsClient35AnalyticsProcessorUsagePointLogData;

@interface _TtC18DVTAnalyticsClient39AnalyticsProcessorUsagePointLogMetaData : DVTAnalyticsData
{
    // Error parsing type: , name: logData
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC18DVTAnalyticsClient35AnalyticsProcessorUsagePointLogData *logData; // @synthesize logData;

@end

