//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTAnalyticsClient/DVTAnalyticsData.h>

@class NSArray;

@interface _TtC18DVTAnalyticsClient53AnalyticsProcessorUsagePointLogMetaStackFrameDataRoot : DVTAnalyticsData
{
    // Error parsing type: , name: root
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSArray *root; // @synthesize root;

@end

