//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@interface _TtC26IDEPegasusPlaygroundEditor33PlaygroundMarginAccessoryProvider : NSObject
{
    // Error parsing type: , name: installed
    // Error parsing type: , name: executionStatusAccessory
    // Error parsing type: , name: delegate
    // Error parsing type: , name: editor
    // Error parsing type: , name: selectedRangeObserver
}

- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

