//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSArray, NSString;

@protocol DVTPlaygroundStubProcess
- (void)setSocketPath:(NSString *)arg1 slaveFileName:(NSString *)arg2 replMode:(BOOL)arg3 resourceDirectoryPath:(NSString *)arg4 completion:(void (^)(int, NSError *))arg5;
- (void)ensureEnvironmentForLibraryPaths:(NSArray *)arg1 frameworkPaths:(NSArray *)arg2 completion:(void (^)(BOOL))arg3;
- (void)reset;
- (void)execute;
@end

