//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <DVTDeviceFoundation/NSCopying-Protocol.h>

@interface DVTNetworkDeviceReachabilityToken : NSObject <NSCopying>
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;

@end

