//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IBCocoaTouchToolFoundation/IBUISimulatedMetricChain.h>

@class IBUISimulatedNavigationItemMetrics;

@interface IBUISimulatedAdaptiveSegueActionMetricChain : IBUISimulatedMetricChain
{
    IBUISimulatedNavigationItemMetrics *_navigationItemMetrics;
    long long _actionType;
    long long _presentationStyleWhenModal;
}

@property(readonly, nonatomic) long long presentationStyleWhenModal; // @synthesize presentationStyleWhenModal=_presentationStyleWhenModal;
@property(readonly, nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(readonly, nonatomic) IBUISimulatedNavigationItemMetrics *navigationItemMetrics; // @synthesize navigationItemMetrics=_navigationItemMetrics;
- (void).cxx_destruct;
- (id)singleLinkPrettyDescription;
- (id)copyWithPrecedingMetric:(id)arg1;
- (BOOL)isEqualToMetricChain:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithNavigationItemMetrics:(id)arg1 actionType:(long long)arg2 presentationStyleWhenModal:(long long)arg3 precedingMetric:(id)arg4;

@end

