//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12SourceEditor14ActionMenuItem : _TtCs12_SwiftObject
{
    // Error parsing type: , name: title
    // Error parsing type: , name: subtitle
    // Error parsing type: , name: icon
    // Error parsing type: , name: cachedTintedIcon
    // Error parsing type: , name: modifierKeys
    // Error parsing type: , name: shortcut
    // Error parsing type: , name: associatedMenuController
}

@end

