//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSImageView.h>

@interface _TtC12SourceEditor35SourceEditorLineAnnotationImageView : NSImageView
{
    // Error parsing type: , name: strokeImage
    // Error parsing type: , name: strokeSize
    // Error parsing type: , name: strokeColor
    // Error parsing type: , name: strokeLayer
    // Error parsing type: , name: maskLayer
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect frame;
- (id)animationForKey:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

