//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12SourceEditorP33_8A34A44A3A81F5AC1210A0E6DECBF3AB31LayoutManagerDataSourceObserver : _TtCs12_SwiftObject
{
    // Error parsing type: , name: layoutManager
}

@end

