//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <SceneKit/SCNKeyedArchiver.h>

@interface SKECloneArchiver : SCNKeyedArchiver
{
}

- (void)encodeObject:(id)arg1 forKey:(id)arg2;

@end

