//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/DVTControllerContentView.h>

@class SKEDisplayOptionPopupController;

@interface SKEDisplayOptionPopupView : DVTControllerContentView
{
    SKEDisplayOptionPopupController *_controller;
}

@property __weak SKEDisplayOptionPopupController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;

@end

