//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

@class NSShadow;

@interface SKEShadowBox : NSView
{
    NSShadow *_boxShadow;
    unsigned long long _shadowedEdges;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1;
@property(nonatomic) unsigned long long shadowedEdges;
@property(copy, nonatomic) NSShadow *boxShadow;
- (id)initWithFrame:(struct CGRect)arg1;

@end

