//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import "_$s12SourceEditor0ab4DataA0CN.h"

#import <DVTSourceEditor/DVTLineRangeCharacterRangeConverter-Protocol.h>

@interface _$s12SourceEditor0ab4DataA0CN (DVTSourceEditor) <DVTLineRangeCharacterRangeConverter>
- (struct _NSRange)lineRangeForCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)characterRangeForLineRange:(struct _NSRange)arg1;
@end

