//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class IDEConsoleItem, IDEPlaygroundExecutionSession, IDEPlaygroundResult, NSError;

@protocol IDEPlaygroundExecutionSessionDelegate
- (void)playgroundExecutionSession:(IDEPlaygroundExecutionSession *)arg1 didEncounterError:(NSError *)arg2;
- (void)playgroundExecutionSession:(IDEPlaygroundExecutionSession *)arg1 didReceiveConsoleItem:(IDEConsoleItem *)arg2;
- (void)playgroundExecutionSession:(IDEPlaygroundExecutionSession *)arg1 didReceiveResult:(IDEPlaygroundResult *)arg2;
- (void)playgroundExecutionSessionDidFinishExecution:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionWillFinishExecution:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionDidFailExpression:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionDidCompleteExpression:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionWillBeginExpression:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionDidBeginExecution:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSessionWillBeginExecution:(IDEPlaygroundExecutionSession *)arg1;
- (void)playgroundExecutionSession:(IDEPlaygroundExecutionSession *)arg1 didMoveToState:(unsigned long long)arg2;
@end

