//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEPlaygroundEditor/IDEPlaygroundDocumentSection.h>

@class NSArray, NSMutableArray, NSString;

@interface IDESourceCodePlaygroundSection : IDEPlaygroundDocumentSection
{
    NSMutableArray *_loggerResults;
    unsigned long long _playgroundResultsGeneration;
    BOOL _incomingResultsAreStale;
    long long _sectionStyle;
    NSString *_originalSourceCode;
    struct _NSRange _originalCodeRange;
}

+ (id)xmlElementName;
+ (void)initialize;
@property(copy) NSString *originalSourceCode; // @synthesize originalSourceCode=_originalSourceCode;
@property struct _NSRange originalCodeRange; // @synthesize originalCodeRange=_originalCodeRange;
@property long long sectionStyle; // @synthesize sectionStyle=_sectionStyle;
@property BOOL incomingResultsAreStale; // @synthesize incomingResultsAreStale=_incomingResultsAreStale;
- (void).cxx_destruct;
- (void)resetPlaygroundSection;
- (id)content;
@property(readonly) NSString *sectionString;
- (void)_setUpTextStorageWithContents:(id)arg1;
@property(readonly) struct _NSRange sectionCharacterRange;
- (id)viewControllerForDisplayingPlaygroundSectionInEditor:(id)arg1;
- (id)initWithSourceCode:(id)arg1 originalSourceCode:(id)arg2 identifier:(id)arg3 inPlaygroundDocument:(id)arg4;

// Remaining properties
@property(copy) NSArray *loggerResults; // @dynamic loggerResults;
@property(readonly, copy) NSMutableArray *mutableLoggerResults; // @dynamic mutableLoggerResults;

@end

