//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDESourceEditor/_TtC15IDESourceEditorP33_7E074BCA936D0EABA73257D5271D839D29ChangeGutterMarginContentView.h>

#import <IDESourceEditor/NSAccessibilityGroup-Protocol.h>

@interface _TtC15IDESourceEditorP33_7E074BCA936D0EABA73257D5271D839D29ChangeGutterMarginContentView (IDESourceEditor) <NSAccessibilityGroup>
- (id)accessibilityLabel;
- (id)accessibilityIdentifier;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
@end

