//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSArray, NSString;

@protocol IDESourceKitRefactoringFileRenameRanges
@property(nonatomic, readonly) NSArray *categorizedRanges;
@property(nonatomic, readonly) BOOL shouldRenameFile;
@property(nonatomic, readonly) NSString *filePath;
@end

