//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderCocoaIntegration/IBToManyCIFilterEffectsInspector.h>

@interface IBContentFiltersEffectsInspector : IBToManyCIFilterEffectsInspector
{
}

- (id)defaultFilterName;
- (id)excludedFilterNamesForFilterChoices;
- (id)excludedCategoriesForFilterChoices;
- (id)localDragPasteboardType;
- (id)noFiltersDisplayString;
- (id)boundFilterKeyPathPrefix;
- (id)inspectedFilterIndexesKeyPath;
- (id)inspectedFilterNameKeyPath;
- (id)bindableFiltersKeyPath;
- (id)nibName;

@end

