//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderCocoaIntegration/NSObject-Protocol.h>

@class IBCocoaBindingsInspectorSlice;

@protocol IBCocoaBindingsInspectorSliceDelegate <NSObject>
- (void)bindingSlice:(IBCocoaBindingsInspectorSlice *)arg1 didChangeExpansionState:(BOOL)arg2;
@end

