//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderKit/IBTargetRuntime.h>

@protocol DVTFontTextFieldDataSource;

@interface IBCocoaTargetRuntime : IBTargetRuntime
{
    id <DVTFontTextFieldDataSource> _fontDataSource;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)displayNameForUserInterfaceStyle;
- (Class)imageRequestProcessorClass;
- (id)toolProxyManager;
- (id)idiom;
@property(readonly) id <DVTFontTextFieldDataSource> fontDataSource; // @synthesize fontDataSource=_fontDataSource;
- (id)colorList;
- (id)archiveIdentifier;
- (id)identifier;
- (id)platform;
- (id)targetRuntimeWithIdiom:(id)arg1;

@end

