//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSArrayController.h>

@interface NSArrayController (IBNSArrayControllerIntegration)
+ (id)ibDynamicShadowedKeyPathsToTypes;
- (id)ibResolvedTypeNameForControllerKey:(id)arg1;
- (id)ibLocalAttributeKeyPaths;

// Remaining properties
@property BOOL ibShadowedAlwaysUsesMultipleValuesMarker; // @dynamic ibShadowedAlwaysUsesMultipleValuesMarker;
@property BOOL ibShadowedAutomaticallyRearrangesObjects; // @dynamic ibShadowedAutomaticallyRearrangesObjects;
@property BOOL ibShadowedAvoidsEmptySelection; // @dynamic ibShadowedAvoidsEmptySelection;
@property BOOL ibShadowedClearsFilterPredicateOnInsertion; // @dynamic ibShadowedClearsFilterPredicateOnInsertion;
@property BOOL ibShadowedPreservesSelection; // @dynamic ibShadowedPreservesSelection;
@property BOOL ibShadowedSelectsInsertedObjects; // @dynamic ibShadowedSelectsInsertedObjects;
@end

