//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSDictionaryController.h>

@class NSArray;

@interface NSDictionaryController (IBNSDictionaryControllerIntegration)
+ (id)ibDynamicShadowedKeyPathsToTypes;
- (BOOL)ibIsInspectorSliceApplicable:(id)arg1 forCategory:(id)arg2;
- (id)ibLocalAttributeKeyPaths;

// Remaining properties
@property(copy) NSArray *ibShadowedExcludedKeys; // @dynamic ibShadowedExcludedKeys;
@property(copy) NSArray *ibShadowedIncludedKeys; // @dynamic ibShadowedIncludedKeys;
@end

