//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSForm.h>

@interface NSForm (IBNSFormIntegration)
- (void)ibPopulateIssues:(id)arg1 forDocument:(id)arg2 withComputationContext:(id)arg3;
- (struct CGSize)ibPreferredCellSize;
- (void)setIbInspectedControlSize:(unsigned long long)arg1;
- (Class)ibEditorClass;
@end

