//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSLevelIndicator.h>

@interface NSLevelIndicator (IBLevelIndicatorIntegration)
+ (id)keyPathsForValuesAffectingIbInspectedCriticalFillColor;
+ (id)keyPathsForValuesAffectingIbInspectedWarningFillColor;
+ (id)keyPathsForValuesAffectingIbInspectedFillColor;
+ (id)keyPathsForValuesAffectingIbStyleIsRating;
+ (id)keyPathsForValuesAffectingIbStyleIsCapacity;
- (void)setIbInspectedCriticalFillColor:(id)arg1;
- (id)ibInspectedCriticalFillColor;
- (void)setIbInspectedWarningFillColor:(id)arg1;
- (id)ibInspectedWarningFillColor;
- (void)setIbInspectedFillColor:(id)arg1;
- (id)ibInspectedFillColor;
- (BOOL)ibSupportsCustomFillColors;
- (BOOL)ibStyleIsRating;
- (BOOL)ibStyleIsCapacity;
- (id)ibInspectedCell;
- (id)ibLocalAttributeKeyPaths;
- (struct CGSize)ibMaximumSize;
- (struct CGSize)ibMinimumSize;
- (double)ibCustomImageHeight;
@end

