//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTMarkup/_TtC9DVTMarkup32PlaygroundMarkupContentBlockView.h>

__attribute__((visibility("hidden")))
@interface _TtC9DVTMarkup14ImageBlockView : _TtC9DVTMarkup32PlaygroundMarkupContentBlockView
{
    // Error parsing type: , name: imageView
    // Error parsing type: , name: altLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;

@end

