//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <SceneKit/NSObject-Protocol.h>

@protocol SCNCameraControlConfiguration <NSObject>
@property(nonatomic) double rotationSensitivity;
@property(nonatomic) double truckSensitivity;
@property(nonatomic) double panSensitivity;
@property(nonatomic) double flyModeVelocity;
@property(nonatomic) BOOL allowsTranslation;
@property(nonatomic) BOOL autoSwitchToFreeCamera;
@end

