//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <SceneKit/SCNRenderer.h>

@interface SCNOffscreenRenderer : SCNRenderer
{
}

+ (id)offscreenRendererWithDevice:(id)arg1 size:(struct CGSize)arg2;
+ (id)offscreenRendererWithContext:(struct _CGLContextObject *)arg1 size:(struct CGSize)arg2;
@property(nonatomic) unsigned long long antialiasingMode;
@property(nonatomic) struct CGSize size;
@property(readonly, nonatomic) unsigned int textureID;
- (id)snapshot;

@end

