//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IBFoundation/IBICDataSet.h>

@interface IBICDataSet (IBICDataSetDisplayAdditions)
+ (CDStruct_7ddbbeae)capsuleGroupingAttributesForGroupWithPath:(id)arg1;
- (id)verifyExistenceInCompiledBundle:(id)arg1 forPlatform:(id)arg2;
- (id)icon;
@end

