//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class IDEBuildOperation, IDEExecutionTracker;

@interface IBLiveViewsTrackedBuildOperation : NSObject
{
    IDEBuildOperation *_buildOperation;
    IDEExecutionTracker *_executionTracker;
}

@property(readonly, nonatomic) IDEExecutionTracker *executionTracker; // @synthesize executionTracker=_executionTracker;
@property(readonly, nonatomic) IDEBuildOperation *buildOperation; // @synthesize buildOperation=_buildOperation;
- (void).cxx_destruct;
- (id)initWithBuildOperation:(id)arg1 executionTracker:(id)arg2;

@end

