//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface IBPlatformToolProxyQueue : NSObject
{
    NSMutableArray *_proxyList;
    NSMutableDictionary *_sessionIDToProxy;
    unsigned long long _nextAvailableIndex;
}

- (void).cxx_destruct;
- (id)description;
- (id)nextProxy;
- (id)toolProxyIncrementingBusyForSessionIdentifier:(id)arg1 includingAlreadyBusy:(BOOL)arg2;
- (void)registerTool:(id)arg1 forPossibleSessionIdentifier:(id)arg2;
- (long long)count;
- (void)addProxy:(id)arg1 registerSessionIdentifierIfNeeded:(id)arg2;
- (void)removeProxy:(id)arg1;
- (id)shutdownAllButOneAfterBlock:(CDUnknownBlockType)arg1;
- (void)shutdownAllAfterBlock:(CDUnknownBlockType)arg1;
- (void)shutdownAndRemoveProxy:(id)arg1;
- (void)shutdownToolsIdleForAtleast:(double)arg1 afterBlock:(CDUnknownBlockType)arg2;

@end

