//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class IBDocument;

@interface IBResourceReferenceUndoPlaceholder : NSObject
{
    IBDocument *_document;
    CDUnknownBlockType _resolutionBlock;
}

@property(readonly, nonatomic) CDUnknownBlockType resolutionBlock; // @synthesize resolutionBlock=_resolutionBlock;
@property(readonly, nonatomic) __weak IBDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)ibTransformValueBeforeApplyingFromUndoStack;
- (id)ibTransformValueBeforePushingOntoUndoStackWithDocument:(id)arg1;
- (id)resolveResource;
- (id)initWithDocument:(id)arg1 resolutionBlock:(CDUnknownBlockType)arg2;

@end

