//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/DVTLayoutView_ML.h>

#import <IDEInterfaceBuilderKit/IBSceneUpdateRequestConfiguring-Protocol.h>

@class NSImage, NSString;
@protocol IBSceneUpdateContentViewDelegate;

@interface IBSceneUpdateContentView : DVTLayoutView_ML <IBSceneUpdateRequestConfiguring>
{
    NSImage *_image;
    double _scaleFactor;
    struct CGRect _lastSceneMaskBounds;
    NSString *_lastSceneMaskIdentifier;
    id <IBSceneUpdateContentViewDelegate> _delegate;
}

@property(nonatomic) __weak id <IBSceneUpdateContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configureSceneUpdateRequest:(id)arg1;
- (void)configureIncrementalSceneUpdateRequest:(id)arg1;
- (void)configureFullSceneUpdateRequest:(id)arg1;
- (void)prepareBezierPathMask:(id)arg1 bounds:(struct CGRect)arg2 forShapeLayer:(id)arg3;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (BOOL)wantsToDrawMask;
- (Class)renderingProcessingRequestClass;
- (id)targetRuntime;
- (struct CGSize)contentSize;
- (id)makeBackingLayer;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

