//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEInterfaceBuilderKit/IBObjCCocoaActionSourceCodeConnectionContext.h>

@interface IBSwiftActionSourceCodeConnectionContext : IBObjCCocoaActionSourceCodeConnectionContext
{
}

+ (BOOL)shouldBePrioritizedWhenInsertingBelowFirstMethod;
- (id)sourceCodeInsertionOptions;
- (id)representativeCounterpart;
- (BOOL)parseSourceLandmarkItem:(id)arg1;
- (id)containingClassName;
- (id)qualifiedType;
- (id)_argumentName;
- (id)defaultType;

@end

