//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSColor, NSDictionary, NSShadow;

@interface IBViewControllerPlaceholderStyle : NSObject
{
    NSShadow *_barShadow;
    NSColor *_backgroundColor;
    NSDictionary *_titleAttributes;
    NSDictionary *_subtitleAttributes;
    NSDictionary *_explanationAttributes;
}

+ (id)styleWithTheme:(id)arg1;
@property(retain, nonatomic) NSDictionary *explanationAttributes; // @synthesize explanationAttributes=_explanationAttributes;
@property(retain, nonatomic) NSDictionary *subtitleAttributes; // @synthesize subtitleAttributes=_subtitleAttributes;
@property(retain, nonatomic) NSDictionary *titleAttributes; // @synthesize titleAttributes=_titleAttributes;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSShadow *barShadow; // @synthesize barShadow=_barShadow;
- (void).cxx_destruct;

@end

