//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC16DVTDocumentation9_TaskList : _TtCs12_SwiftObject
{
    // Error parsing type: , name: pendingTasks
    // Error parsing type: , name: ordersByTask
    // Error parsing type: , name: completedTasksByOrder
    // Error parsing type: , name: nextOrder
    // Error parsing type: , name: prevOrder
}

@end

