//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GameToolsFoundation/NSObject-Protocol.h>

@class GTFActionTimelineModel;

@protocol GTFActionLibraryDelegate <NSObject>
- (void)actionsDidChangeInTimeline:(GTFActionTimelineModel *)arg1;
- (void)didReplaceTimeline:(GTFActionTimelineModel *)arg1 withTimeline:(GTFActionTimelineModel *)arg2;
- (void)didRemoveTimeline:(GTFActionTimelineModel *)arg1;
- (void)didAddTimeline:(GTFActionTimelineModel *)arg1;
@end

