//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GameToolsFoundation/NSObject-Protocol.h>

@class GTFActionRefPreviewPopoverController, GTFActionTimelineModel;

@protocol GTFActionRefPopoverDelegate <NSObject>
- (void)actionRefPopover:(GTFActionRefPreviewPopoverController *)arg1 didPressGotoSourceForTimeline:(GTFActionTimelineModel *)arg2;
@end

