//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <Xcode3Core/DVTPackageInstallerHelperDelegate-Protocol.h>

@class NSError, NSFileHandle, NSString;

@interface FirstLaunchExperienceHelper : NSObject <DVTPackageInstallerHelperDelegate>
{
    NSFileHandle *_outputFileHandle;
    NSError *_installError;
    long long _recordedProgress;
}

+ (id)installPackagesWithOutput:(id)arg1;
+ (BOOL)needToInstallPackages;
@property long long recordedProgress; // @synthesize recordedProgress=_recordedProgress;
@property(retain) NSError *installError; // @synthesize installError=_installError;
@property(retain) NSFileHandle *outputFileHandle; // @synthesize outputFileHandle=_outputFileHandle;
- (void).cxx_destruct;
- (void)installationFailed:(id)arg1;
- (void)installationSucceeded;
- (void)installationProgressChanged:(long long)arg1;
- (void)installationStarted;
- (id)installPackagesAndWait;
- (id)initWithOutput:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

