//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTKit/DVTLayoutView_ML.h>

@class NSTextField;

@interface _TtC18IDESourceControlUI39SourceControlCommitInspectorContentView : DVTLayoutView_ML
{
    // Error parsing type: , name: revisionLabel
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) __weak NSTextField *revisionLabel; // @synthesize revisionLabel;

@end

