//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDESourceControlUI/_TtC18IDESourceControlUI17WorkingCopyEditor.h>

#import <IDESourceControlUI/DVTFindBarFindable-Protocol.h>

@interface _TtC18IDESourceControlUI17WorkingCopyEditor (IDESourceControlUI) <DVTFindBarFindable>
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
@end

