//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEKit/IDEInspectorViewController.h>

@class NSAttributedString;

@interface _TtC18IDESourceControlUI39IDECommitMessageInspectorViewController : IDEInspectorViewController
{
    // Error parsing type: , name: messageFormatted
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) NSAttributedString *messageFormatted; // @synthesize messageFormatted;
- (void)didSetInspectedObjects:(id)arg1;

@end

