//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <IDESourceControlUI/DVTInvalidation-Protocol.h>

@interface _TtC18IDESourceControlUI35SourceControlInvalidatableOperation : NSObject <DVTInvalidation>
{
    // Error parsing type: , name: operation
    // Error parsing type: , name: isValid
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL valid; // @synthesize valid=isValid;
- (BOOL)isValid;
- (void)invalidate;
- (void)primitiveInvalidate;

@end

