//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSImage.h>

@interface NSImage (CSKAdditions)
+ (id)csk_pullDownIconWithColor:(id)arg1;
- (id)csk_imageTintedWithColor:(id)arg1;
@end

