//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class SKAssetReference, SKEditorDocument;

@protocol SKAssetReferenceDelegate
- (BOOL)isAssetStillInWorkspace:(SKAssetReference *)arg1;
- (void)assetReferenceInvalidated:(SKAssetReference *)arg1;
- (void)verifyAssetReferenceIsValid:(SKAssetReference *)arg1 forDocument:(SKEditorDocument *)arg2;
- (void)assetReference:(SKAssetReference *)arg1 didUpdateFromDocument:(SKEditorDocument *)arg2;
@end

