//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDESpriteKitParticleEditor/SKDocumentOperation.h>

@class NSMutableDictionary;

@interface SKModifyUserDataOnTileDefinitionOperation : SKDocumentOperation
{
    id _tileDefinition;
    NSMutableDictionary *_oldUserData;
    NSMutableDictionary *_newUserData;
}

- (void).cxx_destruct;
- (BOOL)_performRevert;
- (BOOL)_performApply;
- (id)initWithDocument:(id)arg1 modifiedUserData:(id)arg2 tileDefinition:(id)arg3;

@end

