//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <SpriteKit/SKShapeNode.h>

@class NSString;

@interface SKShapeNode (InspectorAdditions)
+ (id)keyPathsForValuesAffectingSk_fillTextureImageName;
+ (id)keyPathsForValuesAffectingSk_strokeTextureImageName;
@property(retain, nonatomic) NSString *sk_fillTextureImageName;
@property(retain, nonatomic) NSString *sk_strokeTextureImageName;
@end

