//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <DVTFoundation/_TtP13DVTFoundation20DVTResourceReference_-Protocol.h>

@protocol NSCopying;

@interface _TtC13DVTFoundation28DVTCachableResourceReference : NSObject <_TtP13DVTFoundation20DVTResourceReference_>
{
    // Error parsing type: , name: _cachedKey.storage
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) id <NSCopying> resourceKey;

@end

