//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSPredicate;

@interface DVTFilterExpressionMatcher : NSObject
{
    NSPredicate *_predicate;
}

- (void).cxx_destruct;
- (id)initWithPredicate:(id)arg1;
- (BOOL)matchesObject:(id)arg1;

@end

