//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTITunesConnectServiceResponse.h>

@class NSArray;

@interface DVTITunesConnectVersionsResponse : DVTITunesConnectServiceResponse
{
    NSArray *_versions;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSArray *versions; // @synthesize versions=_versions;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithITunesSoftwareServiceApplicationVersionsResponse:(id)arg1;
- (id)initWithIsSuccessful:(BOOL)arg1 errors:(id)arg2 warnings:(id)arg3 infoMessages:(id)arg4 versions:(id)arg5;

@end

