//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSKeyedArchiver.h>

@interface NSKeyedArchiver (DVTKeyedArchiverAdditions)
+ (id)dvt_archivedDataWithSecureRootObject:(id)arg1 error:(id *)arg2;
+ (id)dvt_archiverRequiringSecureCoding;
+ (id)dvt_archiveDataFromRunningBlock:(CDUnknownBlockType)arg1;
@end

