//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSUnarchiver.h>

@interface NSUnarchiver (DVTArchiverAdditions)
+ (void)dvt_unarchiveData:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
@end

