//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSUndoManager.h>

@interface NSUndoManager (DVTNSUndoManagerAdditions)
+ (void)dvt_applyUndoBlock:(CDUnknownBlockType)arg1;
- (void)dvt_registerUndoBlock:(CDUnknownBlockType)arg1;
@end

