//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTPortal/DVTPortalService.h>

@interface DVTPortalAddPassTypeContainerService : DVTPortalService
{
}

+ (id)addPassTypeContainerServiceWithTeam:(id)arg1 program:(id)arg2 identifier:(id)arg3 name:(id)arg4;

@end

