//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GLToolsServices/DYResource-Protocol.h>

@class NSDictionary;

@protocol DYFramebuffer <DYResource>
@property(readonly, nonatomic) NSDictionary *attachmentsDict;
- (id)initWithProperties:(NSDictionary *)arg1;
@end

