//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GLToolsServices/DYCacheableResource-Protocol.h>
#import <GLToolsServices/NSObject-Protocol.h>

@class NSData;

@protocol DYTextureImageBackingStore <NSObject, DYCacheableResource>
@property(retain, nonatomic) NSData *uncompressedData;
@property(retain, nonatomic) NSData *data;
@end

