//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCSUI/_TtC5XCSUI12XPCOperation.h>

@class XCSXPCACLPayload;

__attribute__((visibility("hidden")))
@interface _TtC5XCSUI26UpdatePermissionsOperation : _TtC5XCSUI12XPCOperation
{
    // Error parsing type: , name: didFinishHandler
    // Error parsing type: , name: newPermissions
}

- (void).cxx_destruct;
- (id)initWithClient:(id)arg1;
- (void)start;
- (id)initWithClient:(id)arg1 payload:(id)arg2 finishHandler:(CDUnknownBlockType)arg3;
@property(nonatomic, retain) XCSXPCACLPayload *newPermissions; // @synthesize newPermissions;
@property(nonatomic, copy) CDUnknownBlockType didFinishHandler; // @synthesize didFinishHandler;

@end

