//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEKit/IDEEditor.h>

#import <XCSUI/DVTReplacementViewDelegate-Protocol.h>

@class DVTObservingToken, NSArray, NSString;

@interface XCSBotEditor : IDEEditor <DVTReplacementViewDelegate>
{
    NSArray *_choices;
    DVTObservingToken *_documentFetchedBotObserver;
    DVTObservingToken *_reportErrorObserver;
}

- (void).cxx_destruct;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)primitiveInvalidate;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

