//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DebuggerFoundation/DBGDataSourceConnectionLegacy.h>

@class NSData;

@interface DBGDataSourceConnectionLegacyPlist : DBGDataSourceConnectionLegacy
{
    BOOL _representsiOSPlist;
    NSData *_plistData;
}

+ (id)connectionForPlistAtPath:(id)arg1;
@property(retain) NSData *plistData; // @synthesize plistData=_plistData;
@property BOOL representsiOSPlist; // @synthesize representsiOSPlist=_representsiOSPlist;
- (void).cxx_destruct;
- (id)targetKitFamilyIdentifier;
- (id)libViewDebuggerSupportClassName;
- (void)simulateDataFetch;
- (id)initWithPlistData:(id)arg1;

@end

