//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <DebuggerFoundation/DBGScreenMaskConfiguration-Protocol.h>

@class NSString;

@interface DBGScreenMaskLegacyConfiguration : NSObject <DBGScreenMaskConfiguration>
{
    NSString *_deviceType;
    long long _displayPixelWidth;
    long long _displayPixelHeight;
    double _displayCornerRadius;
}

+ (id)_knownConfigurations;
+ (id)configurationForDisplayPixelWidth:(long long)arg1 displayPixelHeight:(long long)arg2 displayCornerRadius:(double)arg3;
@property double displayCornerRadius; // @synthesize displayCornerRadius=_displayCornerRadius;
@property long long displayPixelHeight; // @synthesize displayPixelHeight=_displayPixelHeight;
@property long long displayPixelWidth; // @synthesize displayPixelWidth=_displayPixelWidth;
@property(retain) NSString *deviceType; // @synthesize deviceType=_deviceType;
- (void).cxx_destruct;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithPixelWidth:(long long)arg1 pixelHeight:(long long)arg2 cornerRadius:(double)arg3 deviceType:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

