//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSArray, NSString;

@protocol _TtP7XCBuild27XCBTaskConstructionDelegate_
- (void)coreMLModelGeneratedFilePathsWithInputPath:(NSString *)arg1 outputDirPath:(NSString *)arg2 options:(NSArray *)arg3 completion:(void (^)(_TtC7XCBuild22XCBClientRequestResult *))arg4;
- (void)coreDataModelGeneratedFilePathsWithInputPath:(NSString *)arg1 outputDirPath:(NSString *)arg2 swiftVersion:(NSString *)arg3 completion:(void (^)(_TtC7XCBuild22XCBClientRequestResult *))arg4;

@optional
- (void)conservativeSupersetOfAssetTagCombinations:(NSString *)arg1 completion:(void (^)(_TtC7XCBuild22XCBClientRequestResult *))arg2;
- (void)intentDefinitionGeneratedFilePathsWithInputPath:(NSString *)arg1 outputDirPath:(NSString *)arg2 languageToGenerate:(NSString *)arg3 classPrefix:(NSString *)arg4 completion:(void (^)(_TtC7XCBuild22XCBClientRequestResult *))arg5;
@end

