//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSString, _TtC7XCBuild35XCBProvisioningTaskInputsSourceData;

@protocol _TtP7XCBuild28XCBPlanningOperationDelegate_
- (void)provisioningTaskInputsWithTargetGUID:(NSString *)arg1 provisioningSourceData:(_TtC7XCBuild35XCBProvisioningTaskInputsSourceData *)arg2 completion:(void (^)(_TtC7XCBuild25XCBProvisioningTaskInputs *))arg3;
@end

