//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <XCSAdministration/_TtP17XCSAdministration11FileService_-Protocol.h>

@interface _TtC17XCSAdministration18DefaultFileService : NSObject <_TtP17XCSAdministration11FileService_>
{
    // Error parsing type: , name: fileManager
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)setPermissions:(long long)arg1 owner:(id)arg2 group:(id)arg3 at:(id)arg4 error:(id *)arg5;
- (BOOL)symbolicLinkExistsAt:(id)arg1;
- (BOOL)directoryExistsAt:(id)arg1;
- (BOOL)fileExistsAt:(id)arg1;

@end

