//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCV17XCSAdministration15RunRecipeOutputP33_D980F31C533FB11894B0D819402D99A613_StorageClass : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _type
}

@end

