//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <XCSAdministration/_TtP17XCSAdministration14SessionService_-Protocol.h>

@interface _TtC17XCSAdministration21DefaultSessionService : NSObject <_TtP17XCSAdministration14SessionService_>
{
    // Error parsing type: , name: directoryService
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)switchToSessionForUsername:(id)arg1 error:(id *)arg2;
- (void)releaseSessionForUsername:(id)arg1;
- (id)sessionForUsername:(id)arg1;
- (id)initWithDirectoryService:(id)arg1;

@end

