//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <XCSAdministration/XCSInitializationOperation.h>

@interface XCSPingXCSDOperation : XCSInitializationOperation
{
    BOOL _doNotFailWhenDisconnected;
    BOOL _connected;
}

@property(readonly, nonatomic) BOOL connected; // @synthesize connected=_connected;
@property(nonatomic) BOOL doNotFailWhenDisconnected; // @synthesize doNotFailWhenDisconnected=_doNotFailWhenDisconnected;
- (void)run;
- (id)statusDescription;

@end

