//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPURenderTargetEditor/_TtC21GPURenderTargetEditor34GPUTraceSourceSubEditorSidebarView.h>

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor41GPUTraceSourceSubEditorSidebarContentView : _TtC21GPURenderTargetEditor34GPUTraceSourceSubEditorSidebarView
{
    // Error parsing type: , name: sidebar
    // Error parsing type: , name: layoutDelegate
    // Error parsing type: , name: annotations
    // Error parsing type: , name: lineIdentifierToAnnotation
    // Error parsing type: , name: currentDisplayedAnnotations
    // Error parsing type: , name: hoveringAnnotation
}

- (void).cxx_destruct;
- (void)resetCursorRects;
@property(nonatomic, readonly) struct CGRect resizeHitTestRect;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

