//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

@class NSColor;

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor51GPUTraceShaderProfilerAuxiliaryPopoverContainerView : NSView
{
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: backgroundColor
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewDidMoveToWindow;
@property(nonatomic, retain) NSColor *backgroundColor; // @synthesize backgroundColor;
@property(nonatomic, retain) NSView *backgroundView; // @synthesize backgroundView;

@end

