//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC21GPURenderTargetEditor36GPUTraceShaderProfilerOpcodeTypeInfo : _TtCs12_SwiftObject
{
    // Error parsing type: , name: opcodeType
    // Error parsing type: , name: subTypesAndCost
    // Error parsing type: , name: costPercentage
    // Error parsing type: , name: costPercentageBase
}

@end

