//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSTableCellView.h>

@class NSColorWell, NSTextField, _TtC21GPURenderTargetEditor16GPUGLSamplerView;

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor48GPUShaderDebuggerVariableSnapshotSamplerCellView : NSTableCellView
{
    // Error parsing type: , name: minFilterView
    // Error parsing type: , name: magFilterView
    // Error parsing type: , name: mipFilterView
    // Error parsing type: , name: maxAnisotropyView
    // Error parsing type: , name: sAddressModeView
    // Error parsing type: , name: tAddressModeView
    // Error parsing type: , name: rAddressModeView
    // Error parsing type: , name: normalizeCoordinateView
    // Error parsing type: , name: borderColorView
    // Error parsing type: , name: lodMinClampView
    // Error parsing type: , name: lodMaxClampView
    // Error parsing type: , name: lodAverageView
    // Error parsing type: , name: compareFunctionView
    // Error parsing type: , name: samplerView
    // Error parsing type: , name: session
    // Error parsing type: , name: variableSnapshotNode
    // Error parsing type: , name: variableSnapshot
}

+ (double)heightForRegionOfInterestHeight;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setWithSession:(id)arg1 variableSnapshotNode:(id)arg2;
@property(nonatomic, retain) _TtC21GPURenderTargetEditor16GPUGLSamplerView *samplerView; // @synthesize samplerView;
@property(nonatomic, retain) NSTextField *compareFunctionView; // @synthesize compareFunctionView;
@property(nonatomic, retain) NSTextField *lodAverageView; // @synthesize lodAverageView;
@property(nonatomic, retain) NSTextField *lodMaxClampView; // @synthesize lodMaxClampView;
@property(nonatomic, retain) NSTextField *lodMinClampView; // @synthesize lodMinClampView;
@property(nonatomic, retain) NSColorWell *borderColorView; // @synthesize borderColorView;
@property(nonatomic, retain) NSTextField *normalizeCoordinateView; // @synthesize normalizeCoordinateView;
@property(nonatomic, retain) NSTextField *rAddressModeView; // @synthesize rAddressModeView;
@property(nonatomic, retain) NSTextField *tAddressModeView; // @synthesize tAddressModeView;
@property(nonatomic, retain) NSTextField *sAddressModeView; // @synthesize sAddressModeView;
@property(nonatomic, retain) NSTextField *maxAnisotropyView; // @synthesize maxAnisotropyView;
@property(nonatomic, retain) NSTextField *mipFilterView; // @synthesize mipFilterView;
@property(nonatomic, retain) NSTextField *magFilterView; // @synthesize magFilterView;
@property(nonatomic, retain) NSTextField *minFilterView; // @synthesize minFilterView;

@end

