//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPURenderTargetEditor/_TtC21GPURenderTargetEditor45GPUTraceShaderProfilerAuxiliaryViewController.h>

@class NSLayoutConstraint, _TtC21GPURenderTargetEditor47GPUTraceShaderProfilerAuxiliaryVerticleLineView;

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor51GPUTraceShaderProfilerInlineAuxiliaryViewController : _TtC21GPURenderTargetEditor45GPUTraceShaderProfilerAuxiliaryViewController
{
    // Error parsing type: , name: verticleLineView
    // Error parsing type: , name: verticleLineViewXConstraint
    // Error parsing type: , name: containerViewXConstraint
    // Error parsing type: , name: sidebarAnnotations
    // Error parsing type: , name: preferredHeight
    // Error parsing type: , name: didLayoutContent
}

+ (id)instantiateFromStoryboard;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)updateSubAnnotations;
- (void)removeSubAnnotations;
- (void)didLayoutInContentView:(id)arg1;
- (void)fontAndColorThemeDidChange:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic) BOOL didLayoutContent; // @synthesize didLayoutContent;
@property(nonatomic) double preferredHeight; // @synthesize preferredHeight;
@property(nonatomic) __weak NSLayoutConstraint *containerViewXConstraint; // @synthesize containerViewXConstraint;
@property(nonatomic) __weak NSLayoutConstraint *verticleLineViewXConstraint; // @synthesize verticleLineViewXConstraint;
@property(nonatomic) __weak _TtC21GPURenderTargetEditor47GPUTraceShaderProfilerAuxiliaryVerticleLineView *verticleLineView; // @synthesize verticleLineView;

@end

