//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSViewController.h>

@class NSTextField;

__attribute__((visibility("hidden")))
@interface _TtC21GPURenderTargetEditor45GPUShaderDebuggerValueInspectorViewController : NSViewController
{
    // Error parsing type: , name: positionXKeyView
    // Error parsing type: , name: positionYKeyView
    // Error parsing type: , name: positionXValueView
    // Error parsing type: , name: positionYValueView
    // Error parsing type: , name: xKeyView
    // Error parsing type: , name: yKeyView
    // Error parsing type: , name: zKeyView
    // Error parsing type: , name: wKeyView
    // Error parsing type: , name: xValueView
    // Error parsing type: , name: yValueView
    // Error parsing type: , name: zValueView
    // Error parsing type: , name: wValueView
    // Error parsing type: , name: position
    // Error parsing type: , name: pixelValue
}

+ (struct CGSize)popoverContentSizeWithNumberOfComponents:(long long)arg1;
+ (id)instantiateFromStoryboard;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
// Error parsing type for property pixelValue:
// Property attributes: T{DYPixelValue=I(?=[4c][4C][4s][4S][4i][4I][4q][4Q][4 ][4f][4d])},N,VpixelValue

- (void)viewWillAppear;
@property(nonatomic, retain) NSTextField *wValueView; // @synthesize wValueView;
@property(nonatomic, retain) NSTextField *zValueView; // @synthesize zValueView;
@property(nonatomic, retain) NSTextField *yValueView; // @synthesize yValueView;
@property(nonatomic, retain) NSTextField *xValueView; // @synthesize xValueView;
@property(nonatomic, retain) NSTextField *wKeyView; // @synthesize wKeyView;
@property(nonatomic, retain) NSTextField *zKeyView; // @synthesize zKeyView;
@property(nonatomic, retain) NSTextField *yKeyView; // @synthesize yKeyView;
@property(nonatomic, retain) NSTextField *xKeyView; // @synthesize xKeyView;
@property(nonatomic, retain) NSTextField *positionYValueView; // @synthesize positionYValueView;
@property(nonatomic, retain) NSTextField *positionXValueView; // @synthesize positionXValueView;
@property(nonatomic, retain) NSTextField *positionYKeyView; // @synthesize positionYKeyView;
@property(nonatomic, retain) NSTextField *positionXKeyView; // @synthesize positionXKeyView;

@end

