//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPURenderTargetEditor/_TtC21GPURenderTargetEditor46GPUTraceShaderProfilerAnnotationViewController.h>

@interface _TtC21GPURenderTargetEditor46GPUTraceShaderProfilerAnnotationViewController (GPURenderTargetEditor)
- (void)mouseExitedWithPieView:(id)arg1 withEvent:(id)arg2;
- (void)mouseEnteredWithPieView:(id)arg1 withEvent:(id)arg2;
@end

