//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPURenderTargetEditor/DYPShaderDebuggerThread-Protocol.h>

@protocol DYPShaderDebuggerThreadPostTessellationVertex <DYPShaderDebuggerThread>
@property(nonatomic, readonly) float positionInPatchZ;
@property(nonatomic, readonly) float positionInPatchY;
@property(nonatomic, readonly) float positionInPatchX;
@property(nonatomic, readonly) unsigned long long instanceId;
@property(nonatomic, readonly) unsigned long long patchId;
@end

