//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableOrderedSet;

@interface GPUGVNode : NSObject
{
    double x;
    double y;
    double w;
    double h;
    NSMutableOrderedSet *inNodes;
    NSMutableOrderedSet *outNodes;
    long long index;
    GPUGVNode *prev;
    GPUGVNode *next;
    unsigned long long inPriority;
    unsigned long long outPriority;
    BOOL selected;
    int selectedIndex;
    unsigned int _rankType;
    long long rank;
    unsigned long long graphIndex;
    NSMutableArray *slottedOutNodes;
    unsigned long long slots;
    long long _base;
}

@property(nonatomic) long long base; // @synthesize base=_base;
@property(nonatomic) unsigned int rankType; // @synthesize rankType=_rankType;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex;
@property(nonatomic) BOOL selected; // @synthesize selected;
@property(nonatomic) unsigned long long slots; // @synthesize slots;
@property(retain, nonatomic) NSMutableArray *slottedOutNodes; // @synthesize slottedOutNodes;
@property(nonatomic) unsigned long long outPriority; // @synthesize outPriority;
@property(nonatomic) unsigned long long inPriority; // @synthesize inPriority;
@property(retain, nonatomic) GPUGVNode *next; // @synthesize next;
@property(retain, nonatomic) GPUGVNode *prev; // @synthesize prev;
@property(nonatomic) unsigned long long graphIndex; // @synthesize graphIndex;
@property(nonatomic) long long index; // @synthesize index;
@property(nonatomic) long long rank; // @synthesize rank;
@property(retain, nonatomic) NSMutableOrderedSet *outNodes; // @synthesize outNodes;
@property(retain, nonatomic) NSMutableOrderedSet *inNodes; // @synthesize inNodes;
@property(nonatomic) double h; // @synthesize h;
@property(nonatomic) double w; // @synthesize w;
@property(nonatomic) double y; // @synthesize y;
@property(nonatomic) double x; // @synthesize x;
- (void).cxx_destruct;
- (void)traversePreorder:(int)arg1 randomize:(BOOL)arg2 withCallback:(CDUnknownBlockType)arg3;
- (void)traversePostorder:(int)arg1 withCallback:(CDUnknownBlockType)arg2 stopper:(CDUnknownBlockType)arg3 randomize:(BOOL)arg4;
- (id)description;
- (void)computePriority;
- (void)removeEdgeTo:(id)arg1;
- (void)removeEdgeFrom:(id)arg1;
- (void)addEdgeTo:(id)arg1 atSlot:(unsigned long long)arg2;
- (void)addEdgeFrom:(id)arg1 fromOutgoingSlot:(unsigned long long)arg2;
- (BOOL)hasEdgeTo:(id)arg1 atSlot:(unsigned long long)arg2;
- (BOOL)hasEdgeTo:(id)arg1;
- (BOOL)hasEdgeFrom:(id)arg1;
@property(readonly) unsigned long long outDegree;
@property(readonly) unsigned long long inDegree;
@property(nonatomic) struct CGSize size;
@property(nonatomic) struct CGPoint center;
@property(nonatomic) struct CGPoint origin;
@property(nonatomic) struct CGRect frame;
@property(nonatomic) double cy;
@property(nonatomic) double cx;
- (void)dealloc;
- (id)initWithSlots:(unsigned long long)arg1;
- (id)init;

@end

