//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSColor;
@protocol DYResource;

@interface GPURenderOverlayJob : NSObject
{
    BOOL _displayOverlay;
    BOOL _displayOutlineWhenZoomed;
    id <DYResource> _overlayResource;
    NSColor *_overlayColor;
}

@property(retain, nonatomic) NSColor *overlayColor; // @synthesize overlayColor=_overlayColor;
@property(nonatomic) BOOL displayOutlineWhenZoomed; // @synthesize displayOutlineWhenZoomed=_displayOutlineWhenZoomed;
@property(nonatomic) BOOL displayOverlay; // @synthesize displayOverlay=_displayOverlay;
@property(readonly, nonatomic) id <DYResource> overlayResource; // @synthesize overlayResource=_overlayResource;
- (void).cxx_destruct;
- (id)initWithResource:(id)arg1;

@end

