//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class DYRenderingAttributes, GPUTraceModelFactory, NSDictionary, NSString;
@protocol DYResource;

@interface GPURenderJob : NSObject
{
    BOOL _displayRegionOfInterestOverlay;
    id <DYResource> _resource;
    NSDictionary *_overlayResources;
    GPUTraceModelFactory *_modelFactory;
    DYRenderingAttributes *_renderingAttributes;
    id <DYResource> _overlayRenderMask;
    NSString *_displayElementName;
    struct CGRect _overlayRegionOfInterest;
}

@property(readonly, nonatomic) NSString *displayElementName; // @synthesize displayElementName=_displayElementName;
@property(nonatomic) BOOL displayRegionOfInterestOverlay; // @synthesize displayRegionOfInterestOverlay=_displayRegionOfInterestOverlay;
@property(retain, nonatomic) id <DYResource> overlayRenderMask; // @synthesize overlayRenderMask=_overlayRenderMask;
@property(nonatomic) struct CGRect overlayRegionOfInterest; // @synthesize overlayRegionOfInterest=_overlayRegionOfInterest;
@property(retain, nonatomic) DYRenderingAttributes *renderingAttributes; // @synthesize renderingAttributes=_renderingAttributes;
@property(readonly, nonatomic) __weak GPUTraceModelFactory *modelFactory; // @synthesize modelFactory=_modelFactory;
@property(readonly, copy, nonatomic) NSDictionary *overlayResources; // @synthesize overlayResources=_overlayResources;
@property(nonatomic) __weak id <DYResource> resource; // @synthesize resource=_resource;
- (void).cxx_destruct;
- (struct DYInterposeVersion *)usedInterposerVersion;
- (BOOL)wantsDepth;
- (BOOL)flipped;
- (struct CGSize)imageSize;
- (void)resolveWithTraceResourceItem:(id)arg1;
@property(readonly, nonatomic) BOOL isStencilDisplayElement;
@property(readonly, nonatomic) BOOL isDepthDisplayElement;
- (id)initWithResource:(id)arg1 overlayResources:(id)arg2 modelFactory:(id)arg3 textureImageGroupComponent:(unsigned long long)arg4;

@end

