//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <GPURenderTargetEditor/GPUTraceSKBaseNode.h>

#import <GPURenderTargetEditor/SKSelectable-Protocol.h>

@class GPUDebuggerDependencyViewerTextureCache, GPUTraceOutlineItem, GPUTraceSKResourceElement, GPUTraceTitleElement, SKShapeNode;

__attribute__((visibility("hidden")))
@interface GPUTraceSKSimpleEncoderNode : GPUTraceSKBaseNode <SKSelectable>
{
    struct vector<CGPoint, std::__1::allocator<CGPoint>> _slotPositions;
    SKShapeNode *_bg;
    GPUTraceTitleElement *_titleElement;
    GPUTraceSKResourceElement *_selectedResource;
    GPUTraceOutlineItem *_selectedOutlineItem;
    GPUDebuggerDependencyViewerTextureCache *_textureCache;
    double _magnification;
}

@property(nonatomic) double magnification; // @synthesize magnification=_magnification;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)hideStats;
- (void)showStats;
- (void)emphasize;
- (BOOL)acceptTouch:(struct CGPoint)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)emphasizeSlots:(BOOL)arg1;
- (void)emphasizeEdges:(BOOL)arg1;
- (int)selectedSlotIndex;
- (id)selectableOutlineItem;
- (id)mutateIncomingPath:(id)arg1 forEdge:(id)arg2;
- (id)mutateOutgoingPath:(id)arg1 forEdge:(id)arg2;
- (BOOL)hasIssues;
- (void)wire;
- (void)draw;
- (void)updateResoureItemsForImages:(id)arg1;
- (void)loadResourceImages;
- (void)setupResources;
- (id)initWithNode:(id)arg1 withTextureCache:(id)arg2;

@end

