//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSNumber;

__attribute__((visibility("hidden")))
@interface ResourcePair : NSObject
{
    unsigned int _resourceType;
    NSNumber *_resourceId;
}

@property(readonly, nonatomic) unsigned int resourceType; // @synthesize resourceType=_resourceType;
@property(readonly, copy, nonatomic) NSNumber *resourceId; // @synthesize resourceId=_resourceId;
- (void).cxx_destruct;
- (id)initWithId:(id)arg1 resourceType:(unsigned int)arg2;

@end

