//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class DVTExtension;

@interface _IDEDeferredInitializationInvocation : NSObject
{
    Class _initializerClass;
    unsigned long long _options;
    DVTExtension *_extension;
}

- (void).cxx_destruct;
- (void)invokeWithFailureHandler:(CDUnknownBlockType)arg1;
- (id)initWithInitalizerClass:(Class)arg1 options:(unsigned long long)arg2 extension:(id)arg3;

@end

