//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import "_$s13DVTFoundation9DVTSymbolCN.h"

@interface _TtC13IDEFoundation36_IDEObjectiveCSymbolContainingSymbol : _$s13DVTFoundation9DVTSymbolCN
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithResolution:(id)arg1 kind:(id)arg2;
- (id)childSymbolWithObjCName:(id)arg1 kind:(id)arg2 error:(id *)arg3;
- (id)propertySymbolWithObjCName:(id)arg1;
- (id)instanceMethodSymbolWithObjCSignature:(id)arg1;
- (id)classMethodSymbolWithObjCSignature:(id)arg1;

@end

