//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import "_$s16DVTDocumentation0A7ManagerCN.h"

@interface _TtC13IDEFoundation23IDEDocumentationManager : _$s16DVTDocumentation0A7ManagerCN
{
}

+ (id)normalizeSearchQuery:(id)arg1 preservingCase:(BOOL)arg2;
- (id)performSearch:(id)arg1 in:(int)arg2 limit:(long long)arg3 qualityOfService:(long long)arg4 completionBlock:(CDUnknownBlockType)arg5;

@end

