//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTDevice.h>

@class NSArray, NSSet, NSString;

@interface DVTDevice (IDETestingAdditions)
@property(readonly, getter=isLogArchiveCollectionEnabled) BOOL logArchiveCollectionEnabled;
- (BOOL)testRunSpecificationWorkerRequiresUniqueClone:(id)arg1;
@property(readonly) BOOL supportsCloning;
@property(readonly) NSString *mockObjectsFrameworkDir;
@property(readonly) NSSet *processNamesToObserveForCrashReportsDuringTesting;
@property(readonly) NSArray *crashReportsDirectoryPaths;
@property(readonly) NSString *connectionServicesFrameworkPath;
- (BOOL)prepareDeviceForLaunchSession:(id)arg1 error:(id *)arg2;
- (id)claimDeviceForTestingWithSessionIdentifier:(id)arg1;
- (BOOL)supportsTestHostStyle:(long long)arg1 withError:(id *)arg2;
- (id)testArchitectureForBuildableProduct:(id)arg1 buildParameters:(id)arg2;
- (id)internalSystemTestBundleInjectionLibraryPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2;
- (id)testHostPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2 error:(id *)arg3;
- (id)_testingToolPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2;
- (id)internalSystemTestingToolPathForBuildableProduct:(id)arg1 buildParameters:(id)arg2;
- (id)_overriddenTestingToolPathWithBuildableProduct:(id)arg1 buildParameters:(id)arg2;
- (id)testRunnerSessionForConfiguration:(id)arg1;
- (void)requestTestDaemonRecordingSessionWithCompletion:(CDUnknownBlockType)arg1;
- (void)requestTestDaemonControlSessionWithCompletion:(CDUnknownBlockType)arg1;
- (id)testDaemonDTXConnectionProvider;
- (id)makeConnectionForTestDaemonWithError:(id *)arg1;
@property(readonly) BOOL requiresLocalTCCPermissionForUITesting;
@property(readonly) BOOL usesTestDaemonForUIRecording;
@property(readonly) NSString *bridgedProcessAutomationFrameworkPath;
@property(readonly) NSString *automationFrameworkPath;
@property(readonly) NSString *targetBootstrapInjectionPath;
@property(readonly) BOOL supportsTargetBootstrapInjection;
- (Class)testingUIRecorderClass;
@property(readonly) BOOL supportsTestDaemonControlSession;
@property(readonly) BOOL supportsOverridingTestingToolPath;
@property(readonly) BOOL supportsUIRecording;
- (BOOL)supportsUITestingWithError:(id *)arg1;
@end

