//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEActivityLogChangeEvent.h>

@class NSString;

@interface IDEActivityLogAppendTextChangeEvent : IDEActivityLogChangeEvent
{
    NSString *_textString;
}

@property(readonly) NSString *textString; // @synthesize textString=_textString;
- (void).cxx_destruct;
- (id)description;
- (void)writeToLogEventStream:(id)arg1;
- (id)initWithSection:(id)arg1 textString:(id)arg2;

@end

