//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEEntitlementsProcessor.h>

@interface IDEClassKitEntitlementsProcessor : IDEEntitlementsProcessor
{
}

+ (id)availableOptionsForPropertyList;
+ (id)propertyListForContext:(id)arg1;
- (BOOL)loadFromPropertyList:(id)arg1 error:(id *)arg2;
- (BOOL)runWithError:(id *)arg1;
- (BOOL)needsInteraction;

@end

