//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSSet;

@interface IDEDistributionOptionUploadBitcodeState : NSObject
{
    BOOL _uploadBitcode;
    BOOL _bitcodeBalanced;
    unsigned long long _bitcodeLevel;
    NSSet *_platformsWantingAsk;
}

@property(retain) NSSet *platformsWantingAsk; // @synthesize platformsWantingAsk=_platformsWantingAsk;
@property BOOL bitcodeBalanced; // @synthesize bitcodeBalanced=_bitcodeBalanced;
@property unsigned long long bitcodeLevel; // @synthesize bitcodeLevel=_bitcodeLevel;
@property BOOL uploadBitcode; // @synthesize uploadBitcode=_uploadBitcode;
- (void).cxx_destruct;

@end

