//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSError, NSString;

@interface IDEDistributionIssue : NSObject
{
    long long _severity;
    NSError *_error;
}

+ (id)issuesFromErrors:(id)arg1 withSeverity:(long long)arg2;
+ (id)issuesFromITunesResponse:(id)arg1;
@property(readonly) NSError *error; // @synthesize error=_error;
@property(readonly) long long severity; // @synthesize severity=_severity;
- (void).cxx_destruct;
- (id)description;
@property(readonly) NSString *humanReadableDescription;
- (id)initWithSeverity:(long long)arg1 error:(id)arg2;

@end

