//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class DVTITunesConnectAccountCredentials, DVTITunesConnectApplicationDescription, NSData, NSString, NSURL;

@protocol IDEITunesSoftwareServiceProtocol
- (void)dSYMURLForAdamID:(NSString *)arg1 bundleIdentifier:(NSString *)arg2 version:(NSString *)arg3 buildNumber:(NSString *)arg4 platformIdentifier:(NSString *)arg5 accountCredentials:(DVTITunesConnectAccountCredentials *)arg6 callback:(void (^)(NSURL *, NSError *))arg7;
- (void)applicationVersionsForApplicationDecription:(DVTITunesConnectApplicationDescription *)arg1 accountCredentials:(DVTITunesConnectAccountCredentials *)arg2 callback:(void (^)(DVTITunesConnectVersionsResponse *, NSError *))arg3;
- (void)applicationDescriptionsWithAccountCredentials:(DVTITunesConnectAccountCredentials *)arg1 callback:(void (^)(DVTITunesConnectApplicationsResponse *, NSError *))arg2;
- (void)applicationDescriptionWithBundleIdentifier:(NSString *)arg1 platformIdentifier:(NSString *)arg2 accountCredentials:(DVTITunesConnectAccountCredentials *)arg3 callback:(void (^)(DVTITunesConnectApplicationDescription *, NSError *))arg4;
- (void)testDeveloperIDNotificationWithDeviceToken:(NSData *)arg1 accountCredentials:(DVTITunesConnectAccountCredentials *)arg2 callback:(void (^)(DVTITunesConnectDeveloperIDUploadResponse *, NSError *))arg3;
- (void)developerIDStatusResponseForUploadIdentifier:(NSString *)arg1 accountCredentials:(DVTITunesConnectAccountCredentials *)arg2 callback:(void (^)(DVTITunesConnectDeveloperIDStatusResponse *, NSError *))arg3;
- (void)uploadDeveloperIDAppAtPath:(NSString *)arg1 bundleID:(NSString *)arg2 teamID:(NSString *)arg3 deviceToken:(NSData *)arg4 accountCredentials:(DVTITunesConnectAccountCredentials *)arg5 callback:(void (^)(DVTITunesConnectDeveloperIDUploadResponse *, NSError *))arg6;
- (void)uploadInAppPurchaseContentArchiveAtPath:(NSString *)arg1 productID:(NSString *)arg2 application:(DVTITunesConnectApplicationDescription *)arg3 accountCredentials:(DVTITunesConnectAccountCredentials *)arg4 callback:(void (^)(DVTITunesConnectUploadResponse *, NSError *))arg5;
- (void)applicationsWithContentHostedInAppPurchasesForAccountCredentials:(DVTITunesConnectAccountCredentials *)arg1 callback:(void (^)(DVTITunesConnectApplicationsResponse *, NSError *))arg2;
- (void)cancelUploadWithCallback:(void (^)(BOOL, NSError *))arg1;
- (void)uploadApplicationAtPath:(NSString *)arg1 platformIdentifier:(NSString *)arg2 accountCredentials:(DVTITunesConnectAccountCredentials *)arg3 callback:(void (^)(DVTITunesConnectUploadResponse *, NSError *))arg4;
- (void)validationResponseForApplicationAtPath:(NSString *)arg1 platformIdentifier:(NSString *)arg2 accountCredentials:(DVTITunesConnectAccountCredentials *)arg3 callback:(void (^)(DVTITunesConnectServiceResponse *, NSError *))arg4;
- (void)configurationResponseForAccountCredentials:(DVTITunesConnectAccountCredentials *)arg1 bundleID:(NSString *)arg2 toolsBuildVersionName:(NSString *)arg3 callback:(void (^)(DVTITunesConnectConfigurationResponse *, NSError *))arg4;
- (void)configurationResponseForAccountCredentials:(DVTITunesConnectAccountCredentials *)arg1 toolsBuildVersionName:(NSString *)arg2 callback:(void (^)(DVTITunesConnectConfigurationResponse *, NSError *))arg3;
- (void)swinfoFilePathStringWithCallback:(void (^)(NSString *, NSError *))arg1;
- (void)setLogFileURL:(NSURL *)arg1;
@end

