//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <DVTFoundation/DVTOperation.h>

@class DVTFilePath, NSDictionary;

@interface IDELocalizationGenerateStringsForInfoPlistOperation : DVTOperation
{
    NSDictionary *_infoPlistDictionary;
    DVTFilePath *_outputDirectoryFilePath;
    DVTFilePath *_outputStringsFilePath;
}

+ (void)initialize;
@property(copy) DVTFilePath *outputStringsFilePath; // @synthesize outputStringsFilePath=_outputStringsFilePath;
@property(readonly, copy) DVTFilePath *outputDirectoryFilePath; // @synthesize outputDirectoryFilePath=_outputDirectoryFilePath;
@property(readonly, copy) NSDictionary *infoPlistDictionary; // @synthesize infoPlistDictionary=_infoPlistDictionary;
- (void).cxx_destruct;
- (id)stringsFileElementsForKey:(id)arg1 arrayValue:(id)arg2;
- (id)stringsFileElementForKey:(id)arg1 stringValue:(id)arg2;
- (void)main;
- (id)initWithInfoPlistDictionary:(id)arg1 outputDirectoryFilePath:(id)arg2;

@end

