//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSError;

@protocol IDELaunchSessionEventSourceEvents
- (void)launchSessionExpired;
- (void)launchSessionGotPID:(int)arg1;
- (void)launchSessionExitedWithCode:(int)arg1 hasCrashed:(BOOL)arg2;
- (void)launchSessionEncounteredAlertError:(NSError *)arg1;
- (void)launchSessionCompletedInitialIntensiveFileIO;
- (void)launchSessionStarted;
@end

