//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/NSObject-Protocol.h>

@class IDEOnDiskActivityLogRecord, NSString;
@protocol IDELogStoreManageable;

@protocol IDEOnDiskActivityLogRecordManaging <NSObject>
@property(readonly, copy) NSString *rootDirectoryPath;
- (void)cacheLogStoreManageable:(id <IDELogStoreManageable>)arg1 forLogRecord:(IDEOnDiskActivityLogRecord *)arg2;
- (id <IDELogStoreManageable>)cachedLogStoreManageableForLogRecord:(IDEOnDiskActivityLogRecord *)arg1;
- (NSString *)pathForFileName:(NSString *)arg1;
@end

