//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEBreakpoint.h>

@class NSString;

@interface IDESwiftErrorBreakpoint : IDEBreakpoint
{
    NSString *_typeName;
}

@property(copy) NSString *typeName; // @synthesize typeName=_typeName;
- (void).cxx_destruct;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1 version:(id)arg2;
- (id)accessibilityDescription;
- (id)displayName;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

