//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class DVTFilePath, NSArray, NSString;

@protocol IDESourcePackage
@property(readonly) NSArray *packageProducts;
@property(readonly) BOOL isRemotePackage;
@property(readonly) BOOL isRootPackage;
@property(readonly) NSString *packageVersion;
@property(readonly) NSString *packageName;
@property(readonly) DVTFilePath *packagePath;
@property(readonly) NSString *packageURL;
@end

