//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class DVTFilePath, IDESchemeActionResult, IDESchemeActionRunDestinationRecord, IDESchemeCommand, NSDate, NSString;

@interface IDESchemeActionRecord : NSObject
{
    BOOL _debuggerEnabled;
    BOOL _codeCoverageEnabled;
    BOOL _addressSanitizerEnabled;
    BOOL _threadSanitizerEnabled;
    BOOL _undefinedBehaviorSanitizerEnabled;
    IDESchemeCommand *_schemeCommand;
    long long _schemeTask;
    NSString *_title;
    NSDate *_startedTime;
    NSDate *_endedTime;
    NSDate *_corePhaseOperationStartedTime;
    IDESchemeActionResult *_buildResult;
    IDESchemeActionResult *_actionResult;
    NSString *_contextString;
    IDESchemeActionRunDestinationRecord *_runDestinationRecord;
    DVTFilePath *_localRecordDirectoryFilePath;
    DVTFilePath *_creatingWorkspaceFilePath;
}

+ (long long)schemeTaskForString:(id)arg1;
+ (id)stringForSchemeTask:(long long)arg1;
+ (id)schemeCommandForString:(id)arg1;
+ (id)keyPathsForValuesAffectingTestsFailedCount;
+ (id)keyPathsForValuesAffectingTestsCount;
+ (id)keyPathsForValuesAffectingAnalyzerWarningCount;
+ (id)keyPathsForValuesAffectingErrorCount;
+ (id)keyPathsForValuesAffectingWarningCount;
+ (id)keyPathsForValuesAffectingStatus;
+ (BOOL)getSchemeTask:(long long *)arg1 fromDictionaryRepresentation:(id)arg2;
+ (id)keyPathsForValuesAffectingCanSave;
@property(retain, nonatomic) DVTFilePath *creatingWorkspaceFilePath; // @synthesize creatingWorkspaceFilePath=_creatingWorkspaceFilePath;
@property(retain, nonatomic) DVTFilePath *localRecordDirectoryFilePath; // @synthesize localRecordDirectoryFilePath=_localRecordDirectoryFilePath;
@property(retain, nonatomic) IDESchemeActionRunDestinationRecord *runDestinationRecord; // @synthesize runDestinationRecord=_runDestinationRecord;
@property(copy, nonatomic) NSString *contextString; // @synthesize contextString=_contextString;
@property(nonatomic) BOOL undefinedBehaviorSanitizerEnabled; // @synthesize undefinedBehaviorSanitizerEnabled=_undefinedBehaviorSanitizerEnabled;
@property(nonatomic) BOOL threadSanitizerEnabled; // @synthesize threadSanitizerEnabled=_threadSanitizerEnabled;
@property(nonatomic) BOOL addressSanitizerEnabled; // @synthesize addressSanitizerEnabled=_addressSanitizerEnabled;
@property(nonatomic) BOOL codeCoverageEnabled; // @synthesize codeCoverageEnabled=_codeCoverageEnabled;
@property(nonatomic) BOOL debuggerEnabled; // @synthesize debuggerEnabled=_debuggerEnabled;
@property(retain, nonatomic) IDESchemeActionResult *actionResult; // @synthesize actionResult=_actionResult;
@property(retain, nonatomic) IDESchemeActionResult *buildResult; // @synthesize buildResult=_buildResult;
@property(copy, nonatomic) NSDate *corePhaseOperationStartedTime; // @synthesize corePhaseOperationStartedTime=_corePhaseOperationStartedTime;
@property(copy, nonatomic) NSDate *endedTime; // @synthesize endedTime=_endedTime;
@property(copy, nonatomic) NSDate *startedTime; // @synthesize startedTime=_startedTime;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) long long schemeTask; // @synthesize schemeTask=_schemeTask;
@property(retain, nonatomic) IDESchemeCommand *schemeCommand; // @synthesize schemeCommand=_schemeCommand;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long testsFailedCount;
@property(readonly, nonatomic) unsigned long long testsCount;
@property(readonly, nonatomic) unsigned long long analyzerWarningCount;
@property(readonly, nonatomic) unsigned long long errorCount;
@property(readonly, nonatomic) unsigned long long warningCount;
@property(readonly, nonatomic) long long status;
- (id)description;
- (void)close;
- (BOOL)updateWithDictionaryRepresentation:(id)arg1 forSchemeActionsInvocationRecord:(id)arg2;
- (id)dictionaryRepresentationForSchemeActionsInvocationRecord:(id)arg1;
- (BOOL)saveReturningError:(id *)arg1;
- (BOOL)copyResourcesFromSchemeActionRecord:(id)arg1 error:(id *)arg2;
@property(readonly) BOOL canSave;
- (void)recordRunDestination:(id)arg1;
- (id)sparseActionRecordAtFilePath:(id)arg1 testIdentifiers:(id)arg2;
- (id)initWithTitle:(id)arg1 startedTime:(id)arg2 endedTime:(id)arg3 buildResult:(id)arg4 actionResult:(id)arg5 schemeCommand:(id)arg6 runDestinationRecord:(id)arg7;
- (id)initWithLocalRecordDirectoryFilePath:(id)arg1 creatingWorkspaceFilePath:(id)arg2 schemeTask:(long long)arg3;

@end

