//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class IDESourcePackageReference, NSString;

@interface IDESourcePackageProductReference : NSObject
{
    IDESourcePackageReference *_packageReference;
    NSString *_productName;
}

@property(readonly) NSString *productName; // @synthesize productName=_productName;
@property(readonly) IDESourcePackageReference *packageReference; // @synthesize packageReference=_packageReference;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)initWithPackageReference:(id)arg1 productName:(id)arg2;

@end

