//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

@class NSArray, NSString;

@protocol IDESourceKitRefactoringEdit
@property(readonly) NSArray *renameRanges;
@property(readonly) NSString *sourceText;
@property(readonly) long long endColumn;
@property(readonly) long long endLine;
@property(readonly) long long column;
@property(readonly) long long line;
@end

