//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/DVTInvalidation-Protocol.h>

@class DVTOperationGroup, IDETestDestination, IDETestRunSpecification, NSArray, NSURL;
@protocol IDETestTargetRunnerEvents;

@protocol IDETestTargetRunner <DVTInvalidation>
@property(readonly) BOOL successfullyBootstrapped;
@property(readonly) NSURL *artifactsDirectory;
@property(readonly) BOOL finished;
@property(readonly) NSArray *testResults;
@property(readonly) IDETestRunSpecification *testRunSpecification;
@property(readonly) IDETestDestination *testDestination;
@property(readonly) DVTOperationGroup *operation;
@property __weak id <IDETestTargetRunnerEvents> testEventsObserver;
@end

