//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/NSObject-Protocol.h>

@class IDEDeviceAppDataReference, IDELocationScenarioReference, IDEScheme, NSSet;
@protocol IDETestable;

@protocol IDETestingSpecifier <NSObject>
@property(readonly, copy) NSSet *selectedTests;
@property(readonly, copy) NSSet *skippedTests;
@property(readonly) long long testExecutionOrdering;
@property(readonly) BOOL parallelizable;
@property(readonly) BOOL skipped;
@property(readonly) IDELocationScenarioReference *locationScenarioReference;
@property(readonly) IDEDeviceAppDataReference *deviceAppDataReference;
@property(readonly) IDEScheme *scheme;
@property(readonly) id <IDETestable> testable;
@end

