//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDETestableDataSourceToken-Protocol.h>

@class DVTStackBacktrace, IDETestableDataSource, NSString;

@interface IDETestableDataSourceToken : NSObject <IDETestableDataSourceToken>
{
    IDETestableDataSource *_dataSource;
    NSString *_indexableIdentifier;
    CDUnknownBlockType _callbackBlock;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)search;
- (void)primitiveInvalidate;
- (void)_clearDataSource;
- (void)_setTestIdentifiersToTests:(id)arg1;
- (id)initWithDataSource:(id)arg1 indexableIdentifier:(id)arg2 callbackBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

