//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSSplitView.h>

@interface _IDETmpSplitView : NSSplitView
{
    double _dividerThickness;
}

@property double dividerThickness; // @synthesize dividerThickness=_dividerThickness;
- (long long)dividerStyle;
- (id)dividerColor;
- (BOOL)wantsUpdateLayer;

@end

