//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface _IDETestReportTestRunPickerRow : NSObject
{
    NSDate *_firstActivityStartTime;
    NSString *_representedTestIdentifier;
}

@property(copy) NSString *representedTestIdentifier; // @synthesize representedTestIdentifier=_representedTestIdentifier;
@property(copy) NSDate *firstActivityStartTime; // @synthesize firstActivityStartTime=_firstActivityStartTime;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

