//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSTableCellView.h>

@class IDESourceControlWorkingCopyCreationChooserWindowController, NSButton;

@interface DVTProjectWorkingCopyTableCellView : NSTableCellView
{
    IDESourceControlWorkingCopyCreationChooserWindowController *_windowController;
    NSButton *_checkBox;
}

@property NSButton *checkBox; // @synthesize checkBox=_checkBox;
@property IDESourceControlWorkingCopyCreationChooserWindowController *windowController; // @synthesize windowController=_windowController;
- (void)checkBox:(id)arg1;

@end

