//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

@class IDEBuildSchemeAction, NSButton;

@interface IDEBuildRunPhaseOptionsView : NSView
{
    IDEBuildSchemeAction *_runPhase;
    NSView *_contentView;
    NSButton *_buildTimelineCheckbox;
}

@property __weak NSButton *buildTimelineCheckbox; // @synthesize buildTimelineCheckbox=_buildTimelineCheckbox;
@property __weak NSView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) IDEBuildSchemeAction *runPhase; // @synthesize runPhase=_runPhase;
- (void).cxx_destruct;
- (BOOL)showBuildTimeline;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

