//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEKit/IDELaunchActionOptionViewController.h>

@class NSButton, NSLayoutConstraint;

@interface IDEDebugXPCOptionsController : IDELaunchActionOptionViewController
{
    NSButton *_MSLOption;
    NSLayoutConstraint *_verticalSpacingContraint;
}

+ (BOOL)availableForScheme:(id)arg1;
- (void).cxx_destruct;
- (void)loadView;

@end

