//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDEGroup.h>

@interface IDEGroup (InspectorProperties)
+ (id)keyPathsForValuesAffectingHandlesIdeInspectedCanClearRelativeLocation;
+ (id)keyPathsForValuesAffectingIdeInspectedIsNameEditable;
- (id)ideInspectedRelativeLocationContainingFolderPlaceholder;
- (id)ideInspectedRelativeLocationPlaceholder;
- (BOOL)ideInspectedCanClearRelativeLocation;
- (BOOL)ideInspectedRelativeLocationShouldChooseDirectory;
- (BOOL)ideInspectedRelativeLocationShouldChooseFile;
- (BOOL)ideInspectedIsNameEditable;
- (id)applicableInspectorSlicesForCategory:(id)arg1 suggestedSlices:(id)arg2;
@end

