//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEKit/IDESearchFilterControlBar.h>

@class IDENavigator;

@interface IDENavigatorSearchFilterControlBar : IDESearchFilterControlBar
{
}

@property(retain) IDENavigator *navigator;
- (void)setFilterTarget:(id)arg1;
- (void)_didSetFilterTarget;
- (void)_willSetFilterTarget;

@end

