//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSImage, NSTouchBar;

@interface IDESystemModalDebugBarItemState : NSObject
{
    BOOL _enabled;
    BOOL _stateChanged;
    NSImage *_image;
    NSTouchBar *_popoverTouchBar;
    long long _stateValue;
    CDUnknownBlockType _stateDidChangeCallback;
}

@property BOOL stateChanged; // @synthesize stateChanged=_stateChanged;
@property(copy) CDUnknownBlockType stateDidChangeCallback; // @synthesize stateDidChangeCallback=_stateDidChangeCallback;
@property(nonatomic) long long stateValue; // @synthesize stateValue=_stateValue;
@property(retain, nonatomic) NSTouchBar *popoverTouchBar; // @synthesize popoverTouchBar=_popoverTouchBar;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)_actualNotifyStateChanged;
- (void)_coalescedNotifyStateChanged;
- (void)setNeedsStateChangeNotification;

@end

