//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <IDEFoundation/IDESourceControlTreeConflictNode.h>

@interface IDESourceControlTreeConflictNode (IDESourceControlTreeConflictNodeNavigablePropertyAdditions)
+ (id)keyPathsForValuesAffectingNavigableItem_conflictStateForUpdateOrMerge;
- (unsigned long long)navigableItem_conflictStateForUpdateOrMerge;
@end

