//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class NSArray;

@interface IDETimelineGraphDecoratorTickIterator : NSObject
{
    NSArray *_ticks;
    unsigned long long _currentDataIndex;
}

+ (id)iteratorWithTicks:(id)arg1;
@property(readonly, nonatomic) unsigned long long currentDataIndex; // @synthesize currentDataIndex=_currentDataIndex;
- (void).cxx_destruct;
- (void)advanceToTime:(unsigned long long)arg1;
- (void)resetToTime:(unsigned long long)arg1;
- (unsigned long long)_findIndexOfTime:(unsigned long long)arg1 startingAtIndex:(unsigned long long)arg2;
- (id)initWithTicks:(id)arg1;

@end

