//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@class DVTTracePointStringArgument, NSString;

@interface DVTTracePointDomain : NSObject
{
    unsigned long long _options;
    unsigned int _classSubclassPortion;
    DVTTracePointStringArgument *_domainIdentifierAsArgument;
    NSString *_identifier;
}

+ (id)globalDomain;
+ (void)initialize;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, getter=isRecording) BOOL recording;
- (id)initWithIdentifier:(id)arg1 options:(unsigned long long)arg2;
- (id)init;

@end

