//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <objc/NSObject.h>

@interface _TtC29IDESourceCodeComparisonEditor18BlameVisualization : NSObject
{
    // Error parsing type: , name: sourceEditorView
    // Error parsing type: , name: blameController
    // Error parsing type: , name: blameItemsByLine
    // Error parsing type: , name: blameItemsToLineLayers
    // Error parsing type: , name: installedBlameItems
}

- (void).cxx_destruct;
- (id)init;
- (void)createAnnotations;
- (void)removeFromSourceEditorView:(id)arg1;
- (void)addToSourceEditorView:(id)arg1;
- (id)initWithBlameController:(id)arg1;

@end

