//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <AppKit/NSView.h>

#import <IDESourceCodeComparisonEditor/NSAccessibilityButton-Protocol.h>

@class CALayer, CAShapeLayer, CATextLayer, DVTFontAndColorTheme, IDEBlameAnnotationBackgroundView, NSColor, NSDictionary, NSFont, NSString, NSTextField;
@protocol IDEBlameAnnotationViewDelegate;

@interface IDEBlameAnnotationView : NSView <NSAccessibilityButton>
{
    NSFont *_defaultFont;
    NSFont *_defaultBoldFont;
    double _defaultFontSize;
    NSColor *_titleColor;
    NSColor *_subtitleColor;
    NSColor *_subtitleLinkColor;
    IDEBlameAnnotationBackgroundView *_backgroundView;
    CALayer *_highlightLayer;
    CALayer *_hoverLayer;
    CAShapeLayer *_circleLayer;
    BOOL _dirtyView;
    CATextLayer *_displayLogItemDateLayer;
    CATextLayer *_displayAuthorLayer;
    CALayer *_leftBorderLayer;
    CALayer *_topBorderLayer;
    NSDictionary *_layerActions;
    DVTFontAndColorTheme *_theme;
    BOOL _highlighted;
    BOOL _uncommitted;
    BOOL _hideTopBorder;
    id <IDEBlameAnnotationViewDelegate> _delegate;
    NSTextField *_messageTextField;
    NSString *_date;
    NSString *_author;
    NSString *_message;
}

+ (id)annotationActiveHighlightColor;
+ (BOOL)_hasLightBackround;
+ (double)defaultWidthWithFontSize:(double)arg1;
+ (double)defaultWidth;
+ (id)_boldFontWithSize:(double)arg1;
+ (id)_fontWithFontSize:(double)arg1;
+ (double)_defaultFontSize;
+ (id)annotationHighlightColor;
+ (id)annotationHighlightGradient;
+ (id)annotationActiveHighlightGradient;
@property(nonatomic) BOOL hideTopBorder; // @synthesize hideTopBorder=_hideTopBorder;
@property(nonatomic) BOOL uncommitted; // @synthesize uncommitted=_uncommitted;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *date; // @synthesize date=_date;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(readonly, nonatomic) NSTextField *messageTextField; // @synthesize messageTextField=_messageTextField;
@property(nonatomic) __weak id <IDEBlameAnnotationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)viewDidChangeBackingProperties;
- (void)viewDidChangeEffectiveAppearance;
- (void)updateHighlightLayerBackgroundColor;
- (void)updateLayer;
- (void)reloadMessageTextField;
- (void)_updateFontAndTheme;
- (id)urlFromClickBounds;
- (void)_updateAuthorDateAgeAndBorderFrames;
- (void)_updateMessageFrame;
- (BOOL)_singleLine;
- (BOOL)wantsUpdateLayer;
- (void)disableHover;
- (void)enableHover:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

