//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <Foundation/NSString.h>

@interface NSString (DBGNumberDecoding)
- (id)dbgDataValue;
- (id)dbgStringValue;
- (double)dbgCGFloatValue;
- (unsigned long long)dbgUnsignedIntegerValue;
- (long long)dbgIntegerValue;
- (unsigned long long)dbgUnsignedLongValue;
- (long long)dbgLongValue;
- (unsigned int)dbgUnsignedIntValue;
- (int)dbgIntValue;
- (double)dbgDoubleValue;
- (float)dbgFloatValue;
- (BOOL)dbgBoolValue;
@end

