//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC15XCBBuildService7Session20PIFTransferOperation : _TtCs12_SwiftObject
{
    // Error parsing type: , name: session
    // Error parsing type: , name: loadingSession
    // Error parsing type: , name: workspaceSignature
    // Error parsing type: , name: hasFailed
    // Error parsing type: , name: comparisonWorkspace
}

@end

