//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX-I.sdk
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC15XCBBuildServiceP33_7162B1E1A07B81DFE4339C845C50F70323TaskOutputParserHandler : _TtCs12_SwiftObject
{
    // Error parsing type: , name: diagnosticsEngine
    // Error parsing type: , name: buildRequest
    // Error parsing type: , name: taskID
    // Error parsing type: , name: targetID
    // Error parsing type: , name: handler
}

@end

